import React from "react";
import CreateVoucherTicket from "../components/CreateVoucherTicket/CreateVoucherTicket";
import BookActivationReport from "../containers/BookActivationReport/BookActivationReport";
import BookOrderReport from "../containers/BookOrderReports/BookOrderReports";
import ConsumerReports from "../containers/ConsumerReport/ConsumerReport";
import SalesReport from "../containers/SalesReports/SalesReports";
import UserLoginReport from "../containers/UserLoginReport";
import VoucherRedemptionReport from "../containers/VoucherRedemptionReport/VoucherRedemptionReport";
import AddEditBookPurchaseProvider from "../providers/AddEditBookPurchaseRequest.provider";
import AddEditBookSubscriptionProvider from "../providers/addEditBookSubscription.provider";
import AddEditBrandProvider from "../providers/addEditBrand.provider";
import AddEditItemProvider from "../providers/addEditItem.provider";
import AdminManagementProvider from "../providers/adminManagement.provider";
import AreaSegmentProvider from "../providers/areaSegment.provider";
import BookManagementProvider from "../providers/bookManagement.provider";
import BookOrderManagementProvider from "../providers/bookOrderManagement.provider";
import BookSubscriptionManagementProvider from "../providers/bookSubscriptionManagement.provider";
import BrandManagementProvider from "../providers/brandManagement.provider";
import CampaignDesignerProvider from "../providers/campaignDesigner.provider";
import ConsumerManagementProvider from "../providers/consumerManagement.provider";
import CorporateCustomerManagementProvider from "../providers/corporateCustomerManagement.provider";
import DealCategoryManagementProvider from "../providers/dealCategoryManagement.provider";
import DealManagementProvider from "../providers/dealManagement.provider";
import LandingPageDesignerProvider from "../providers/landingPageDesigner.provider";
import LandingPageManagementProvider from "../providers/landingPageManagement.provider";
import MerchantManagementProvider from "../providers/merchantManagement.provider";
import MusalliMosqueManagementProvider from "../providers/musalliMosqueManagement.provider";
import MusalliParticipantManagementProvider from "../providers/musalliParticipantManagement.provider";
import MusalliPaymentManagementProvider from "../providers/musalliPaymentManagement.provider";
import MusalliSessionManagementProvider from "../providers/musalliSessionManagement.provider";
import MusalliVolunteerManagementProvider from "../providers/musalliVolunteerManagement.provider";
import OutletBillingManagementProvider from "../providers/outletBIllingManagementProvider";
import PartnerManagementProvider from "../providers/partnerManagement.provider";
import SessionManagementProvider from "../providers/SessionManagment.provider";
import VoucherRedemptionManagementProvider from "../providers/VoucherRedemptionManagement.provider";
import AddEditParticipantProvider from "../providers/addEditParticipant.provider";
import AddEditVolunteerProvider from "../providers/addEditVolunteer.provider";
import AddEditMosqueProvider from "../providers/addEditMosque.provider";
import AddEditSessionProvider from "../providers/addEditSession.provider";
import AddEditPaymentProvider from "../providers/addEditPayment.provider";

import BaitussalamWebAndAppProjectManagementProvider from "../providers/baitussalamWeb&AppProjectManagement.provider";
import AddEditBaitussalamWebAndAppProjectManagementProvider from "../providers/addEditBaitussalamProjectManagement.provider";
import BaitussalamWebAndAppEventManagementProvider from "../providers/baitussalamWeb&AppEventManagement.provider";
import AddEditBaitussalamWebAndAppEventManagementProvider from "../providers/addEditBaitussalamEventManagement.provider";
import BaitussalamWebAndAppNaatUsersManagementProvider from "../providers/baitussalamWeb&AppNaatUsersManagement.provider";
import AddEditBaitussalamWebAndAppNaatUsersManagementProvider from "../providers/addEditBaitussalamNaatUsersManagement.provider";
import BaitussalamWebAndAppGalleryManagementProvider from "../providers/baitussalamWeb&AppGalleryManagement.provider";
import AddEditBaitussalamWebAndGalleryManagementProvider from "../providers/addEditBaitussalamGalleryManagement.provider";
import BaitussalamWebAndAppNewsManagementProvider from "../providers/baitussalamWeb&AppNewsManagement.provider";
import AddEditBaitussalamWebAndNewsManagementProvider from "../providers/addEditBaitussalamNewsManagement.provider";
import BaitussalamWebAndAppBayanatCategoryManagementProvider from "../providers/baitussalamWeb&AppBayanatCategoryManagement.provider";
import AddEditBaitussalamWebAndBayanatCategoryManagementProvider from "../providers/addEditBaitussalamBayanatCategoryManagement.provider";
import BaitussalamWebAndAppBayanaatManagementProvider from "../providers/baitussalamWeb&AppBayanaatManagement.provider";
import AddEditBaitussalamWebAndBayanaatManagementProvider from "../providers/addEditBaitussalamBayanaatManagement.provider";
import BaitussalamWebAndAppPublicationCategoryManagementProvider from "../providers/baitussalamWeb&AppPublicationCategoryManagement.provider";
import AddEditBaitussalamWebAndPublicationCategoryManagementProvider from "../providers/addEditBaitussalamPublicationCategoryManagement.provider";
import BaitussalamWebAndAppPublicationsManagementProvider from "../providers/baitussalamWeb&AppPublicationsManagement.provider";
import AddEditBaitussalamWebAndPublicationsManagementProvider from "../providers/addEditBaitussalamPublicationsManagement.provider";

import BaitussalamWebAndAppGuideManagementProvider from "../providers/baitussalamWeb&AppGuideManagement.provider";
import AddEditBaitussalamWebAndGuideManagementProvider from "../providers/addEditBaitussalamGuideManagement.provider";
import BaitussalamWebAndAppPartnerManagementProvider from "../providers/baitussalamWeb&AppPartnerManagement.provider";
import AddEditBaitussalamWebAndPartnerManagementProvider from "../providers/addEditBaitussalamPartnerManagement.provider";
import BaitussalamWebAndNewslatterManagementProvider from "../providers/baitussalamWeb&AppNewslatterManagement.provider";
import BaitussalamWebAndAdminUsersManagementProvider from "../providers/baitussalamWeb&AppAdminUsersManagement.provider";
import AddEditBaitussalamWebAndAdminUsersManagementProvider from "../providers/addEditbaitussalamAdminUsersManagement.provider";
import BaitussalamWebAndVolunteerManagementProvider from "../providers/baitussalamWeb&AppVolunteerManagement.provider";
import AddEditBaitussalamWebAndVolunteerManagementProvider from "../providers/addEditBaitussalamVolunteerManagement.provider";
import BaitussalamWebAndVideoManagementProvider from "../providers/baitussalamWeb&AppVideoManagement.provider";
import AddEditBaitussalamWebAndVideoManagementProvider from "../providers/addEditBaitussalamVideoManagement.provider";
import BaitussalamWebAndDuaCategoryManagementProvider from "../providers/baitussalamWeb&AppDuaCaategoryManagement.provider";
import AddEditBaitussalamWebAndDuaCategoryManagementProvider from "../providers/addEditBaitussalamDuaCategoryManagement.provider";
import BaitussalamWebAndDuasManagementProvider from "../providers/baitussalamWeb&AppDuasManagement.provider";
import AddEditBaitussalamWebAndDuasManagementProvider from "../providers/addEditBaitussalamDuasManagement.provider";
import BaitussalamWebAndFeaturedVideoManagementProvider from "../providers/baitussalamWeb&AppFeaturedVideoManagement.provider";
import AddEditBaitussalamWebAndFeaturedVideoManagementProvider from "../providers/addEditBaitussalamFeaturedVideoManagement.provider";
import BaitussalamWebAndFeaturedBannerManagementProvider from "../providers/baitussalamWeb&AppFeaturedBannerManagement.provider";
import AddEditBaitussalamWebAndFeaturedBannerManagementProvider from "../providers/addEditBaitussalamFeaturedBannerManagement.provider";
import BaitussalamWebAndOnlineCharityManagementProvider from "../providers/baitussalamWeb&AppOnlineCharityManagement.provider";
import AddEditBaitussalamWebAndOnlineCharityManagementProvider from "../providers/addEditBaitussalamOnlineCharityManagement.provider";
import BaitussalamWebAndDonationCategoryManagementProvider from "../providers/baitussalamWeb&AppDonationCategoryManagement.provider";
import AddEditBaitussalamWebAndDonationCategoryManagementProvider from "../providers/addEditBaitussalamDonationCategoryManagement.provider";
import BaitussalamWebAndDonationCustomerManagementProvider from "../providers/baitussalamWeb&AppCustomerManagement.provider";
import AddEditBaitussalamWebAndDonationCustomerManagementProvider from "../providers/addEditBaitussalamCustomerManagement.provider";
import BaitussalamWebAndHijriDateManagementProvider from "../providers/baitussalamWeb&AppHijriDateManagement.provider";
import BaitussalamWebAndSaibanManagementProvider from "../providers/baitussalamWeb&AppSaibanManagement.provider";
import AddEditBaitussalamWebAndSaibanManagementProvider from "../providers/addEditBaitussalamSaibanManagement.provider";
import BaitussalamWebAndSettingManagementProvider from "../providers/baitussalamWeb&AppSettingManagement.provider";
import AddEditBaitussalamWebAndSettingManagementProvider from "../providers/addEditBaitussalamSettingManagement.provider";

import ROUTES from "./constant.route";

const ChangePasswordProvider = React.lazy(() => import("../providers/changePassword.provider"));

const BookOrderReportsProvider = React.lazy(() => import("../providers/bookOrderPurchaseReports.provider"));
const DashboardProvider = React.lazy(() => import("../providers/dashboard.provider"));
const MerchantDashboardProvider = React.lazy(() => import("../providers/merchantDashboard.provider"));

const ProfileProvider = React.lazy(() => import("../providers/profile.provider"));

const AddEditDealProvider = React.lazy(() => import("../providers/addEditDeal.provider"));
const AddEditCorporateCustomerProvider = React.lazy(() => import("../providers/addEditCorporateCustomer.provider"));
const AddEditPartnerProvider = React.lazy(() => import("../providers/addEditPartner.provider"));
const ViewPartnerProvider = React.lazy(() => import("../providers/viewPartner.provider"));
const PartnerProfileProvider = React.lazy(() => import("../providers/partnerProfile.provider"));
const AddEditCampaignProvider = React.lazy(() => import("../providers/addEditCampaign.provider"));
const SwimLaneManagerProvider = React.lazy(() => import("../providers/swimLaneManager.provider"));
// const AddAreaSegmentProvider=React.lazy(()=>import("../providers/addAreaSegmentManagement.provider"))
// const EditAreaSegmentProvider=React.lazy(()=>import("../providers/editAreaSegmentManagement.provider"))

const AddEditAreaSegmentProvider = React.lazy(() => import("../providers/addEditAreaSegment.provider"));

const AddEditBookProvider = React.lazy(() => import("../providers/addEditBookManagement.provider"));
const AddEditProfilerProvider = React.lazy(() => import("../providers/addEditProfiler.provider"));

// const AddAdminUserProvider = React.lazy(() => import("../providers/addAdmin.provider"));
// const EditAdminUserProvider = React.lazy(() => import("../providers/editAdmin.provider"));

const AddEditAdminProvider = React.lazy(() => import("../providers/addEditAdmin.provider"));

const AddEditConsumerProvider = React.lazy(() => import("../providers/addEditConsumer.provider"));

const AddEditDealCategoryProvider = React.lazy(() => import("../providers/addEditDealCategory.provider"));

const campaignStatusConsoleProvider = React.lazy(() => import("../providers/campaignStatusConsole.provider"));
const ViewCampaignStatisticsProvider = React.lazy(() => import("../providers/viewCampaignStatistics.provider"));

const AddEditMerchantUserProvider = React.lazy(() => import("../providers/addEditMerchant.provider"));
const MerchantProfileProvider = React.lazy(() => import("../providers/merchantProfile.provider"));
const AddEditVoucherRedemptionProvider = React.lazy(() => import("../providers/addEditVoucherRedemption.provider"));

// Home

// User Management
//   Admin Management
//   Merchant Management
//   Consumer Management

// Partner Management
//   Area Segment Management
//   Brand Management
//   Partner Management

// Deal Management
//   Category Management
//   Deal Management
//   Book Management
//   Campaign Management
//   Books Purchase Requests

// Reports
//   Deal Redeem Reports
//   Book Purchase Reports
//   Campaign Reports

const routes = [
  {
    path: `${ROUTES.CHANGE_PASSWORD.path}/:id`,
    exact: true,
    name: ROUTES.CHANGE_PASSWORD.name,
    displayName: ROUTES.CHANGE_PASSWORD.title,
    component: ChangePasswordProvider,
    isPrivate: true,
    icon: "HomeOutlined",
    isHiddenInMenu: true,
    hideInSideBar: true,
    module: 0,
    category: "ChangePassword",
    action: "View",
  },
  {
    path: ROUTES.DASHBOARD.path,
    exact: true,
    name: ROUTES.DASHBOARD.name,
    displayName: ROUTES.DASHBOARD.title,
    component: DashboardProvider,
    isPrivate: true,
    icon: "HomeOutlined",
    isDisabled: false,
    module: 0,
    category: "Home",
    action: "View",
  },
  {
    path: ROUTES.PROFILE.path,
    exact: true,
    name: ROUTES.PROFILE.name,
    displayName: ROUTES.PROFILE.title,
    component: ProfileProvider,
    isPrivate: true,
    icon: "ProfileOutlined",
    isHiddenInMenu: true,
    module: 0,
    category: "Profile",
    action: "View",
  },
  {
    path: ROUTES.SESSION_MANAGEMENT.path,
    exact: true,
    name: ROUTES.SESSION_MANAGEMENT.name,
    displayName: ROUTES.SESSION_MANAGEMENT.title,
    component: SessionManagementProvider,
    isPrivate: true,
    icon: "SmileOutlined",
    isDisabled: false,
    module: 1,
    category: "UserManagement",
    subCategory: "Session",
    action: "List",
  },
  {
    path: ROUTES.ADMIN_MANAGEMENT.path,
    exact: true,
    name: ROUTES.ADMIN_MANAGEMENT.name,
    displayName: ROUTES.ADMIN_MANAGEMENT.title,
    component: AdminManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 1,
    category: "UserManagement",
    subCategory: "Admin",
    action: "List",
  },
  {
    path: ROUTES.ADD_ADMIN_USER.path,
    exact: true,
    name: ROUTES.ADD_ADMIN_USER.name,
    displayName: ROUTES.ADD_ADMIN_USER.title,
    component: AddEditAdminProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: true,
    module: 0,
    hideInSideBar: true,
    parentRouteName: ROUTES.ADMIN_MANAGEMENT.name,
    category: "UserManagement",
    subCategory: "Admin",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_ADMIN_USER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_ADMIN_USER.name,
    displayName: ROUTES.EDIT_ADMIN_USER.title,
    component: AddEditAdminProvider,
    isPrivate: true,
    icon: "setting",
    module: 0,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.ADMIN_MANAGEMENT.name,
    category: "UserManagement",
    subCategory: "Admin",
    action: "Edit",
  },
  {
    path: ROUTES.MERCHANT_MANAGEMENT.path,
    exact: true,
    name: ROUTES.MERCHANT_MANAGEMENT.name,
    displayName: ROUTES.MERCHANT_MANAGEMENT.title,
    component: MerchantManagementProvider,
    isPrivate: true,
    icon: "StarOutlined",
    isDisabled: false,
    module: 1,
    category: "UserManagement",
    subCategory: "Merchant",
    action: "List",
  },
  {
    path: ROUTES.ADD_MERCHANT_USER.path,
    exact: true,
    name: ROUTES.ADD_MERCHANT_USER.name,
    displayName: ROUTES.ADD_MERCHANT_USER.title,
    component: AddEditMerchantUserProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: true,
    module: 0,
    hideInSideBar: true,
    parentRouteName: ROUTES.MERCHANT_MANAGEMENT.name,
    category: "UserManagement",
    subCategory: "Merchant",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_MERCHANT_USER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_MERCHANT_USER.name,
    displayName: ROUTES.EDIT_MERCHANT_USER.title,
    component: AddEditMerchantUserProvider,
    isPrivate: true,
    icon: "setting",
    module: 0,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.MERCHANT_MANAGEMENT.name,
    category: "UserManagement",
    subCategory: "Merchant",
    action: "Edit",
  },
  {
    path: `${ROUTES.MERCHANT_PROFILE.path}`,
    exact: true,
    name: ROUTES.MERCHANT_PROFILE.name,
    displayName: ROUTES.MERCHANT_PROFILE.title,
    component: MerchantProfileProvider,
    isPrivate: true,
    icon: "setting",
    module: 0,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.MERCHANT_MANAGEMENT.name,
    category: "UserManagement",
    subCategory: "Merchant",
    action: "Profile",
  },
  {
    path: ROUTES.CONSUMER_MANAGEMENT.path,
    exact: true,
    name: ROUTES.CONSUMER_MANAGEMENT.name,
    displayName: ROUTES.CONSUMER_MANAGEMENT.title,
    component: ConsumerManagementProvider,
    isPrivate: true,
    icon: "AccountBookOutlined",
    module: 1,
    category: "UserManagement",
    subCategory: "Consumer",
    action: "List",
  },
  {
    path: ROUTES.ADD_CONSUMER_USER.path,
    exact: true,
    name: ROUTES.ADD_CONSUMER_USER.name,
    displayName: ROUTES.ADD_CONSUMER_USER.title,
    component: AddEditConsumerProvider,
    isPrivate: true,
    icon: "user",
    isHiddenInMenu: true,
    hideInSideBar: true,
    module: 1,
    parentRouteName: ROUTES.CONSUMER_MANAGEMENT.name,
    category: "UserManagement",
    subCategory: "Consumer",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_CONSUMER_USER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_CONSUMER_USER.name,
    displayName: ROUTES.EDIT_CONSUMER_USER.title,
    component: AddEditConsumerProvider,
    isPrivate: true,
    icon: "user",
    isHiddenInMenu: true,
    hideInSideBar: true,
    module: 1,
    parentRouteName: ROUTES.CONSUMER_MANAGEMENT.name,
    category: "UserManagement",
    subCategory: "Consumer",
    action: "Edit",
  },
  {
    path: ROUTES.AREA_SEGMENT_MANAGEMENT.path,
    exact: true,
    name: ROUTES.AREA_SEGMENT_MANAGEMENT.name,
    displayName: ROUTES.AREA_SEGMENT_MANAGEMENT.title,
    component: AreaSegmentProvider,
    isPrivate: true,
    icon: "PushpinOutlined",
    module: 2,
    category: "PartnerManagement",
    subCategory: "AreaSegment",
    action: "List",
  },
  {
    path: ROUTES.ADD_PARTNER.path,
    exact: true,
    name: ROUTES.ADD_PARTNER.name,
    displayName: ROUTES.ADD_PARTNER.title,
    component: AddEditPartnerProvider,
    isPrivate: true,
    icon: "team",
    isHiddenInMenu: true,
    module: 2,
    hideInSideBar: true,
    parentRouteName: ROUTES.PARTNER_MANAGEMENT.name,
    category: "PartnerManagement",
    subCategory: "Partner",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_PARTNER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_PARTNER.name,
    displayName: ROUTES.EDIT_PARTNER.title,
    component: AddEditPartnerProvider,
    isPrivate: true,
    icon: "team",
    isHiddenInMenu: true,
    module: 2,
    hideInSideBar: true,
    parentRouteName: ROUTES.PARTNER_MANAGEMENT.name,
    category: "PartnerManagement",
    subCategory: "Partner",
    action: "Edit",
  },
  {
    path: `${ROUTES.VIEW_PARTNER.path}/:id`,
    exact: true,
    name: ROUTES.VIEW_PARTNER.name,
    displayName: ROUTES.VIEW_PARTNER.title,
    component: ViewPartnerProvider,
    isPrivate: true,
    icon: "team",
    isHiddenInMenu: true,
    module: 2,
    hideInSideBar: true,
    parentRouteName: ROUTES.PARTNER_MANAGEMENT.name,
    category: "PartnerManagement",
    subCategory: "Partner",
    action: "View",
  },
  {
    path: `${ROUTES.PARTNER_PROFILE.path}`,
    exact: true,
    name: ROUTES.PARTNER_PROFILE.name,
    displayName: ROUTES.PARTNER_PROFILE.title,
    component: PartnerProfileProvider,
    isPrivate: true,
    icon: "team",
    isHiddenInMenu: true,
    module: 2,
    hideInSideBar: true,
    parentRouteName: ROUTES.PARTNER_MANAGEMENT.name,
    category: "PartnerManagement",
    subCategory: "Partner",
    action: "Profile",
  },

  {
    path: ROUTES.BRAND_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BRAND_MANAGEMENT.name,
    displayName: ROUTES.BRAND_MANAGEMENT.title,
    component: BrandManagementProvider,
    isPrivate: true,
    icon: "MoneyCollectOutlined",
    module: 2,
    category: "PartnerManagement",
    subCategory: "Brand",
    action: "List",
  },

  {
    path: ROUTES.ADD_AREA_SEGMENT.path,
    exact: true,
    name: ROUTES.ADD_AREA_SEGMENT.name,
    displayName: ROUTES.ADD_AREA_SEGMENT.title,
    component: AddEditAreaSegmentProvider,
    isPrivate: true,
    icon: "environment",
    module: 2,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.AREA_SEGMENT_MANAGEMENT.name,
    category: "PartnerManagement",
    subCategory: "AreaSegment",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_AREA_SEGMENT.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_AREA_SEGMENT.name,
    displayName: ROUTES.EDIT_AREA_SEGMENT.title,
    component: AddEditAreaSegmentProvider,
    isPrivate: true,
    icon: "environment",
    module: 2,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.AREA_SEGMENT_MANAGEMENT.name,
    category: "PartnerManagement",
    subCategory: "AreaSegment",
    action: "Edit",
  },
  {
    path: ROUTES.PARTNER_MANAGEMENT.path,
    exact: true,
    name: ROUTES.PARTNER_MANAGEMENT.name,
    displayName: ROUTES.PARTNER_MANAGEMENT.title,
    component: PartnerManagementProvider,
    isPrivate: true,
    icon: "MobileOutlined",
    module: 2,
    category: "PartnerManagement",
    subCategory: "Partner",
    action: "List",
  },
  {
    path: `${ROUTES.EDIT_BRAND.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BRAND.name,
    displayName: ROUTES.EDIT_BRAND.title,
    component: AddEditBrandProvider,
    isPrivate: true,
    isHiddenInMenu: true,
    hideInSideBar: true,
    icon: "barcode",
    module: 2,
    category: "PartnerManagement",
    subCategory: "Brand",
    action: "Edit",
  },
  {
    path: ROUTES.ADD_BRAND.path,
    exact: true,
    name: ROUTES.ADD_BRAND.name,
    displayName: ROUTES.ADD_BRAND.title,
    component: AddEditBrandProvider,
    isPrivate: true,
    isHiddenInMenu: true,
    hideInSideBar: true,
    icon: "barcode",
    module: 2,
    category: "PartnerManagement",
    subCategory: "Brand",
    action: "Add",
  },
  {
    path: ROUTES.CATEGORY_MANAGEMENT.path,
    exact: true,
    name: ROUTES.CATEGORY_MANAGEMENT.name,
    displayName: ROUTES.CATEGORY_MANAGEMENT.title,
    component: DealCategoryManagementProvider,
    isPrivate: true,
    icon: "DollarOutlined",
    module: 3,
    category: "VoucherManagement",
    subCategory: "Category",
    action: "List",
  },
  {
    path: ROUTES.ADD_DEAL.path,
    exact: true,
    name: ROUTES.ADD_DEAL.name,
    displayName: ROUTES.ADD_DEAL.title,
    component: AddEditDealProvider,
    isPrivate: true,
    icon: "user",
    isHiddenInMenu: true,
    hideInSideBar: true,
    module: 3,
    parentRouteName: ROUTES.DEAL_MANAGEMENT.name,
    category: "VoucherManagement",
    subCategory: "Voucher",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_DEAL.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_DEAL.name,
    displayName: ROUTES.EDIT_DEAL.title,
    component: AddEditDealProvider,
    isPrivate: true,
    icon: "user",
    isHiddenInMenu: true,
    hideInSideBar: true,
    module: 3,
    parentRouteName: ROUTES.DEAL_MANAGEMENT.name,
    category: "VoucherManagement",
    subCategory: "Voucher",
    action: "Edit",
  },

  {
    path: ROUTES.DEAL_MANAGEMENT.path,
    exact: true,
    name: ROUTES.DEAL_MANAGEMENT.name,
    displayName: ROUTES.DEAL_MANAGEMENT.title,
    component: DealManagementProvider,
    isPrivate: true,
    icon: "AccountBookOutlined",
    module: 3,
    category: "VoucherManagement",
    subCategory: "Voucher",
    action: "List",
  },

  {
    path: ROUTES.ADD_CATEGORY.path,
    exact: true,
    name: ROUTES.ADD_CATEGORY.name,
    displayName: ROUTES.ADD_CATEGORY.title,
    component: AddEditDealCategoryProvider,
    isPrivate: true,
    icon: "user",
    isHiddenInMenu: true,
    hideInSideBar: true,
    module: 1,
    parentRouteName: ROUTES.CATEGORY_MANAGEMENT.name,
    category: "VoucherManagement",
    subCategory: "Category",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_CATEGORY.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_CATEGORY.name,
    displayName: ROUTES.EDIT_CATEGORY.title,
    component: AddEditDealCategoryProvider,
    isPrivate: true,
    icon: "user",
    isHiddenInMenu: true,
    hideInSideBar: true,
    module: 1,
    parentRouteName: ROUTES.CATEGORY_MANAGEMENT.name,
    category: "VoucherManagement",
    subCategory: "Category",
    action: "Edit",
  },
  {
    path: ROUTES.BOOK_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BOOK_MANAGEMENT.name,
    displayName: ROUTES.BOOK_MANAGEMENT.title,
    component: BookManagementProvider,
    isPrivate: true,
    icon: "BookOutlined",
    module: 3,
    category: "VoucherManagement",
    subCategory: "Book",
    action: "List",
  },
  {
    path: ROUTES.ADD_BOOK.path,
    exact: true,
    name: ROUTES.ADD_BOOK.name,
    displayName: ROUTES.ADD_BOOK.title,
    component: AddEditBookProvider,
    isPrivate: true,
    icon: "book",
    module: 3,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.BOOK_MANAGEMENT.name,
    category: "VoucherManagement",
    subCategory: "Book",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BOOK.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BOOK.name,
    displayName: ROUTES.EDIT_BOOK.title,
    component: AddEditBookProvider,
    isPrivate: true,
    icon: "book",
    module: 3,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.BOOK_MANAGEMENT.name,
    category: "VoucherManagement",
    subCategory: "Book",
    action: "Edit",
  },

  {
    path: ROUTES.BOOK_PURCHASE_REQUESTS.path,
    exact: true,
    name: ROUTES.BOOK_PURCHASE_REQUESTS.name,
    displayName: ROUTES.BOOK_PURCHASE_REQUESTS.title,
    component: () => ROUTES.BOOK_PURCHASE_REQUESTS.title,
    isPrivate: true,
    icon: "BookOutlined",
    module: 3,
    category: "VoucherManagement",
    subCategory: "BookPurchaseRequest",
    action: "List",
  },
  {
    path: ROUTES.BOOK_ORDERS.path,
    exact: true,
    name: ROUTES.BOOK_ORDERS.name,
    displayName: ROUTES.BOOK_ORDERS.title,
    component: BookOrderManagementProvider,
    isPrivate: true,
    icon: "MobileOutlined",
    module: 4,
    category: "BookSubscriptionManagement",
    subCategory: "BookOrderManagement",
    action: "List",
  },
  {
    path: ROUTES.NEW_REQUEST.path,
    exact: true,
    name: ROUTES.NEW_REQUEST.name,
    displayName: ROUTES.NEW_REQUEST.title,
    component: AddEditBookPurchaseProvider,
    isPrivate: true,
    hideInSideBar: true,
    icon: "solution",
    module: 4,
    category: "BookSubscriptionManagement",
    subCategory: "BookOrderManagement",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_NEW_REQUEST.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_NEW_REQUEST.name,
    displayName: ROUTES.EDIT_NEW_REQUEST.title,
    component: AddEditBookPurchaseProvider,
    isPrivate: true,
    hideInSideBar: true,
    icon: "solution",
    module: 4,
    category: "BookSubscriptionManagement",
    subCategory: "BookOrderManagement",
    action: "Edit",
  },
  {
    path: ROUTES.CORPORATE_CUSTOMER_MANAGEMENT.path,
    exact: true,
    name: ROUTES.CORPORATE_CUSTOMER_MANAGEMENT.name,
    displayName: ROUTES.CORPORATE_CUSTOMER_MANAGEMENT.title,
    component: CorporateCustomerManagementProvider,
    isPrivate: true,
    icon: "StarOutlined",
    module: 4,
    category: "BookSubscriptionManagement",
    subCategory: "CorporateCustomer",
    action: "List",
  },
  {
    path: ROUTES.ADD_CORPORATE_CUSTOMER.path,
    exact: true,
    name: ROUTES.ADD_CORPORATE_CUSTOMER.name,
    displayName: ROUTES.ADD_CONSUMER_USER.title,
    component: AddEditCorporateCustomerProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: true,
    module: 4,
    hideInSideBar: true,
    parentRouteName: ROUTES.CORPORATE_CUSTOMER_MANAGEMENT.name,
    category: "BookSubscriptionManagement",
    subCategory: "CorporateCustomer",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_CORPORATE_CUSTOMER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_CORPORATE_CUSTOMER.name,
    displayName: ROUTES.EDIT_CORPORATE_CUSTOMER.title,
    component: AddEditCorporateCustomerProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: true,
    module: 4,
    hideInSideBar: true,
    parentRouteName: ROUTES.CORPORATE_CUSTOMER_MANAGEMENT.name,
    category: "BookSubscriptionManagement",
    subCategory: "CorporateCustomer",
    action: "Edit",
  },
  {
    path: ROUTES.BOOK_SUBSCRIPTION_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BOOK_SUBSCRIPTION_MANAGEMENT.name,
    displayName: ROUTES.BOOK_SUBSCRIPTION_MANAGEMENT.title,
    component: BookSubscriptionManagementProvider,
    isPrivate: true,
    icon: "solution",
    module: 4,
    category: "BookSubscriptionManagement",
    subCategory: "BookSubscription",
    action: "List",
  },
  {
    path: ROUTES.ADD_BOOK_SUBSCRIPTION.path,
    exact: true,
    name: ROUTES.ADD_BOOK_SUBSCRIPTION.name,
    parentRouteName: ROUTES.BOOK_SUBSCRIPTION_MANAGEMENT.name,
    displayName: ROUTES.ADD_BOOK_SUBSCRIPTION.title,
    component: AddEditBookSubscriptionProvider,
    isPrivate: true,
    hideInSideBar: true,
    icon: "solution",
    module: 4,
    category: "BookSubscriptionManagement",
    subCategory: "BookSubscription",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BOOK_SUBSCRIPTION.path}/:id`,
    exact: true,
    name: ROUTES.ADD_BOOK_SUBSCRIPTION.name,
    parentRouteName: ROUTES.BOOK_SUBSCRIPTION_MANAGEMENT.name,
    displayName: ROUTES.ADD_BOOK_SUBSCRIPTION.title,
    component: AddEditBookSubscriptionProvider,
    isPrivate: true,
    hideInSideBar: true,
    icon: "solution",
    module: 4,
    category: "BookSubscriptionManagement",
    subCategory: "BookSubscription",
    action: "Edit",
  },
  {
    path: ROUTES.VOUCHER_REDEMPTION_MANAGEMENT.path,
    exact: true,
    name: ROUTES.VOUCHER_REDEMPTION_MANAGEMENT.name,
    displayName: ROUTES.VOUCHER_REDEMPTION_MANAGEMENT.title,
    component: VoucherRedemptionManagementProvider,
    isPrivate: true,
    icon: "tags",
    module: 11,
    category: "VoucherRedemptionManagement",
    subCategory: "VoucherRedemption",
    action: "List",
  },
  {
    path: ROUTES.ADD_VOUCHER_REDEMPTION.path,
    exact: true,
    name: ROUTES.ADD_VOUCHER_REDEMPTION.name,
    displayName: ROUTES.ADD_VOUCHER_REDEMPTION.title,
    component: CreateVoucherTicket,
    isPrivate: true,
    hideInSideBar: false,
    parentRouteName: ROUTES.VOUCHER_REDEMPTION_MANAGEMENT.name,
    icon: "tags",
    module: 11,
    category: "VoucherRedemptionManagement",
    subCategory: "VoucherRedemption",
    action: "Add",
  },
  {
    path: ROUTES.MERCHANT_DASHBOARD.path,
    exact: true,
    name: ROUTES.MERCHANT_DASHBOARD.name,
    displayName: ROUTES.MERCHANT_DASHBOARD.title,
    component: MerchantDashboardProvider,
    isPrivate: true,
    icon: "HomeOutlined",
    isDisabled: false,
    module: 5,
    category: "MerchantHome",
    action: "View",
  },
  {
    path: `${ROUTES.EDIT_VOUCHER_REDEMPTION.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_VOUCHER_REDEMPTION.name,
    displayName: ROUTES.EDIT_VOUCHER_REDEMPTION.title,
    component: AddEditVoucherRedemptionProvider,
    isPrivate: true,
    hideInSideBar: true,
    icon: "tags",
    module: 11,
    category: "VoucherRedemptionManagement",
    subCategory: "VoucherRedemption",
    action: "Edit",
  },
  {
    path: ROUTES.CAMPAIGN_DESIGNER.path,
    exact: true,
    name: ROUTES.CAMPAIGN_DESIGNER.name,
    displayName: ROUTES.CAMPAIGN_DESIGNER.title,
    component: CampaignDesignerProvider,
    isPrivate: true,
    icon: "StarOutlined",
    module: 6,
    category: "PromotionManagement",
    subCategory: "CampaignDesigner",
    action: "List",
  },
  {
    path: `${ROUTES.CAMPAIGN_STATUS_VIEW.path}/:id`,
    exact: true,
    name: ROUTES.CAMPAIGN_STATUS_VIEW.name,
    displayName: ROUTES.CAMPAIGN_STATUS_VIEW.title,
    component: ViewCampaignStatisticsProvider,
    parentRouteName: ROUTES.CAMPAIGN_STATUS_VIEW.name,
    isPrivate: true,
    hideInSideBar: true,
    icon: "tags",
    module: 6,
    category: "PromotionManagement",
    subCategory: "CampaignStatus",
    action: "View",
  },
  {
    path: ROUTES.CAMPAIGN_STATUS.path,
    exact: true,
    name: ROUTES.CAMPAIGN_STATUS.name,
    displayName: ROUTES.CAMPAIGN_STATUS.title,
    component: campaignStatusConsoleProvider,
    isPrivate: true,
    icon: "tags",
    module: 6,
    category: "PromotionManagement",
    subCategory: "CampaignStatus",
    action: "List",
  },
  {
    path: ROUTES.ADD_CAMPAIGN.path,
    exact: true,
    name: ROUTES.ADD_CAMPAIGN.name,
    displayName: ROUTES.ADD_CAMPAIGN.title,
    component: AddEditCampaignProvider,
    isPrivate: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.CAMPAIGN_DESIGNER.name,
    icon: "StarOutlined",
    module: 6,
    category: "PromotionManagement",
    subCategory: "CampaignDesigner",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_CAMPAIGN.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_CAMPAIGN.name,
    displayName: ROUTES.EDIT_CAMPAIGN.title,
    component: AddEditCampaignProvider,
    isPrivate: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.CAMPAIGN_DESIGNER.name,
    icon: "StarOutlined",
    module: 6,
    category: "PromotionManagement",
    subCategory: "CampaignDesigner",
    action: "Edit",
  },
  {
    path: ROUTES.BOOK_ORDER_REPORT.path,
    exact: true,
    name: ROUTES.BOOK_ORDER_REPORT.name,
    displayName: ROUTES.BOOK_ORDER_REPORT.title,
    component: BookOrderReport,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 10,
    category: "ReportsManagement",
    subCategory: "BookOrderReport",
    action: "List",
  },
  {
    path: ROUTES.BOOK_ACTIVATION_REPORT.path,
    exact: true,
    name: ROUTES.BOOK_ACTIVATION_REPORT.name,
    displayName: ROUTES.BOOK_ACTIVATION_REPORT.title,
    component: BookActivationReport,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 10,
    category: "ReportsManagement",
    subCategory: "BookActivationReport",
    action: "List",
  },
  {
    path: ROUTES.VOUCHER_REDEMPTION_REPORT.path,
    exact: true,
    name: ROUTES.VOUCHER_REDEMPTION_REPORT.name,
    displayName: ROUTES.VOUCHER_REDEMPTION_REPORT.title,
    component: VoucherRedemptionReport,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 10,
    category: "ReportsManagement",
    subCategory: "VoucherRedemptionReport",
    action: "List",
  },
  {
    path: ROUTES.SALES_REPORT.path,
    exact: true,
    name: ROUTES.SALES_REPORT.name,
    displayName: ROUTES.SALES_REPORT.title,
    component: SalesReport,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 10,
    category: "ReportsManagement",
    subCategory: "SalesReport",
    action: "List",
  },
  {
    path: ROUTES.CONSUMER_REPORT.path,
    exact: true,
    name: ROUTES.CONSUMER_REPORT.name,
    displayName: ROUTES.CONSUMER_REPORT.title,
    component: ConsumerReports,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 10,
    category: "ReportsManagement",
    subCategory: "ConsumerReports",
    action: "List",
  },
  {
    path: ROUTES.USER_LOGIN_REPORT.path,
    exact: true,
    name: ROUTES.USER_LOGIN_REPORT.name,
    displayName: ROUTES.USER_LOGIN_REPORT.title,
    component: UserLoginReport,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 10,
    category: "ReportsManagement",
    subCategory: "UserLoginReport",
    action: "List",
  },
  // {
  //   path: ROUTES.DEAL_REDEEM_REPORTS.path,
  //   exact: true,
  //   name: ROUTES.DEAL_REDEEM_REPORTS.name,
  //   displayName: ROUTES.DEAL_REDEEM_REPORTS.title,
  //   component: () => ROUTES.DEAL_REDEEM_REPORTS.title,
  //   isPrivate: true,
  //   icon: "BarChartOutlined",
  //   module: 10,
  //   category: "ReportsManagement",
  //   subCategory: "DealRedeem",
  //   action: "List",
  // },
  // {
  //   path: ROUTES.BOOK_PURCHASE_REPORT.path,
  //   exact: true,
  //   name: ROUTES.BOOK_PURCHASE_REPORT.name,
  //   displayName: ROUTES.BOOK_PURCHASE_REPORT.title,
  //   component: BookOrderReportsProvider,
  //   isPrivate: true,
  //   icon: "BarChartOutlined",
  //   module: 10,
  //   category: "ReportsManagement",
  //   subCategory: "BookPurchase",
  //   action: "List",
  // },
  // {
  //   path: ROUTES.CAMPAIGN_REPORT.path,
  //   exact: true,
  //   name: ROUTES.CAMPAIGN_REPORT.name,
  //   displayName: ROUTES.CAMPAIGN_REPORT.title,
  //   component: () => ROUTES.CAMPAIGN_REPORT.title,
  //   isPrivate: true,
  //   icon: "BarChartOutlined",
  //   module: 10,
  //   category: "ReportsManagement",
  //   subCategory: "Campaign",
  //   action: "List",
  // },
  {
    path: ROUTES.LANDING_PAGE_MANAGEMENT.path,
    exact: true,
    name: ROUTES.LANDING_PAGE_MANAGEMENT.name,
    displayName: ROUTES.LANDING_PAGE_MANAGEMENT.title,
    component: LandingPageManagementProvider,
    isPrivate: true,
    icon: "BarChartOutlined",
    isDisabled: false,
    module: 8,
    category: "LandingManagement",
    subCategory: "Profiler",
    action: "List",
  },
  {
    path: `${ROUTES.SWIM_LANE_MANAGER.path}/:id`,
    exact: true,
    name: ROUTES.SWIM_LANE_MANAGER.name,
    displayName: ROUTES.SWIM_LANE_MANAGER.title,
    component: SwimLaneManagerProvider,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 8,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.LANDING_PAGE_MANAGEMENT.name,
    category: "LandingManagement",
    subCategory: "Profiler",
    action: "Add",
  },
  {
    path: ROUTES.ADD_PROFILER.path,
    exact: true,
    name: ROUTES.ADD_PROFILER.name,
    displayName: ROUTES.ADD_PROFILER.title,
    component: AddEditProfilerProvider,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 8,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.LANDING_PAGE_MANAGEMENT.name,
    category: "LandingManagement",
    subCategory: "Profiler",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_PROFILER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_PROFILER.name,
    displayName: ROUTES.EDIT_PROFILER.title,
    component: AddEditProfilerProvider,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 8,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.LANDING_PAGE_MANAGEMENT.name,
    category: "LandingManagement",
    subCategory: "Profiler",
    action: "Edit",
  },
  {
    path: `${ROUTES.LANDING_PAGE_DESIGNER.path}/:id`,
    exact: true,
    name: ROUTES.LANDING_PAGE_DESIGNER.name,
    displayName: ROUTES.LANDING_PAGE_DESIGNER.title,
    component: LandingPageDesignerProvider,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 8,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.LANDING_PAGE_MANAGEMENT.name,
    category: "LandingManagement",
    subCategory: "Designer",
    action: "Edit",
  },
  // Phase-1 Work
  {
    path: ROUTES.OUTLET_BILLING_MANAGMENT.path,
    exact: true,
    name: ROUTES.OUTLET_BILLING_MANAGMENT.name,
    displayName: ROUTES.OUTLET_BILLING_MANAGMENT.title,
    component: OutletBillingManagementProvider,
    isPrivate: true,
    icon: "UsergroupAddOutlined",
    module: 2,
    category: "PartnerManagement",
    subCategory: "OutletBillingManagement",
    action: "List",
  },
  {
    path: ROUTES.ADD_ITEM.path,
    exact: true,
    name: ROUTES.ADD_ITEM.name,
    displayName: ROUTES.ADD_ITEM.title,
    component: AddEditItemProvider,
    isPrivate: true,
    // icon: "",
    isHiddenInMenu: true,
    hideInSideBar: true,
    // module: ,
    // parentRouteName: ,
    category: "RestaurantManagement",
    subCategory: "Item",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_ITEM.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_ITEM.name,
    displayName: ROUTES.EDIT_ITEM.title,
    component: AddEditItemProvider,
    isPrivate: true,
    // icon: "",
    isHiddenInMenu: true,
    hideInSideBar: true,
    // module: ,
    // parentRouteName: ,
    category: "RestaurantManagement",
    subCategory: "Item",
    action: "Edit",
  },

  // Musalli Routes

  // {
  //   path: ROUTES.MUSALLI_ADMIN_MANAGEMENT.path,
  //   exact: true,
  //   name: ROUTES.MUSALLI_ADMIN_MANAGEMENT.name,
  //   displayName: ROUTES.MUSALLI_ADMIN_MANAGEMENT.title,
  //   component: AdminManagementProvider,
  //   isPrivate: true,
  //   icon: "HeartOutlined",
  //   module: 12,
  //   category: "MusalliManagement",
  //   subCategory: "Musalli",
  //   action: "List",
  // },
  // {
  //   path: ROUTES.ADD_MUSALLI_ADMIN_USER.path,
  //   exact: true,
  //   name: ROUTES.ADD_MUSALLI_ADMIN_USER.name,
  //   displayName: ROUTES.ADD_MUSALLI_ADMIN_USER.title,
  //   component: AddEditAdminProvider,
  //   isPrivate: true,
  //   icon: "setting",
  //   isHiddenInMenu: false,
  //   module: 12,
  //   hideInSideBar: true,
  //   parentRouteName: ROUTES.ADMIN_MANAGEMENT.name,
  //   category: "MusalliManagement",
  //   subCategory: "Musalli",
  //   action: "Add",
  // },
  // {
  //   path: `${ROUTES.EDIT_MUSALLI_ADMIN_USER.path}/:id`,
  //   exact: true,
  //   name: ROUTES.EDIT_MUSALLI_ADMIN_USER.name,
  //   displayName: ROUTES.EDIT_MUSALLI_ADMIN_USER.title,
  //   component: AddEditAdminProvider,
  //   isPrivate: true,
  //   icon: "setting",
  //   module: 12,
  //   isHiddenInMenu: false,
  //   hideInSideBar: true,
  //   parentRouteName: ROUTES.ADMIN_MANAGEMENT.name,
  //   category: "MusalliManagement",
  //   subCategory: "Musalli",
  //   action: "Edit",
  // },
  {
    path: ROUTES.MUSALLI_PARTICIPANT_MANAGEMENT.path,
    exact: true,
    name: ROUTES.MUSALLI_PARTICIPANT_MANAGEMENT.name,
    displayName: ROUTES.MUSALLI_PARTICIPANT_MANAGEMENT.title,
    component: MusalliParticipantManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 12,
    category: "MusalliManagement",
    subCategory: "Musalli",
    action: "List",
  },
  {
    path: ROUTES.ADD_MUSALLI_PARTICIPANT_USER.path,
    exact: true,
    name: ROUTES.ADD_MUSALLI_PARTICIPANT_USER.name,
    displayName: ROUTES.ADD_MUSALLI_PARTICIPANT_USER.title,
    component: AddEditParticipantProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 12,
    hideInSideBar: true,
    parentRouteName: ROUTES.MUSALLI_PARTICIPANT_MANAGEMENT.name,
    category: "MusalliManagement",
    subCategory: "Musalli",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_MUSALLI_PARTICIPANT_USER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_MUSALLI_PARTICIPANT_USER.name,
    displayName: ROUTES.EDIT_MUSALLI_PARTICIPANT_USER.title,
    component: AddEditParticipantProvider,
    isPrivate: true,
    icon: "setting",
    module: 12,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.MUSALLI_PARTICIPANT_MANAGEMENT.name,
    category: "MusalliManagement",
    subCategory: "Musalli",
    action: "Edit",
  },
  {
    path: ROUTES.MUSALLI_VOLUNTEER_MANAGEMENT.path,
    exact: true,
    name: ROUTES.MUSALLI_VOLUNTEER_MANAGEMENT.name,
    displayName: ROUTES.MUSALLI_VOLUNTEER_MANAGEMENT.title,
    component: MusalliVolunteerManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 12,
    category: "MusalliManagement",
    subCategory: "Musalli",
    action: "List",
  },
  {
    path: ROUTES.ADD_MUSALLI_VOLUNTEER_USER.path,
    exact: true,
    name: ROUTES.ADD_MUSALLI_VOLUNTEER_USER.name,
    displayName: ROUTES.ADD_MUSALLI_VOLUNTEER_USER.title,
    component: AddEditVolunteerProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 12,
    hideInSideBar: true,
    parentRouteName: ROUTES.MUSALLI_VOLUNTEER_MANAGEMENT.name,
    category: "MusalliManagement",
    subCategory: "Musalli",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_MUSALLI_VOLUNTEER_USER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_MUSALLI_VOLUNTEER_USER.name,
    displayName: ROUTES.EDIT_MUSALLI_VOLUNTEER_USER.title,
    component: AddEditVolunteerProvider,
    isPrivate: true,
    icon: "setting",
    module: 12,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.MUSALLI_VOLUNTEER_MANAGEMENT.name,
    category: "MusalliManagement",
    subCategory: "Musalli",
    action: "Edit",
  },
  {
    path: ROUTES.MUSALLI_MOSQUE_MANAGEMENT.path,
    exact: true,
    name: ROUTES.MUSALLI_MOSQUE_MANAGEMENT.name,
    displayName: ROUTES.MUSALLI_MOSQUE_MANAGEMENT.title,
    component: MusalliMosqueManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 12,
    category: "MusalliManagement",
    subCategory: "Musalli",
    action: "List",
  },
  {
    path: ROUTES.ADD_MUSALLI_MOSQUE_USER.path,
    exact: true,
    name: ROUTES.ADD_MUSALLI_MOSQUE_USER.name,
    displayName: ROUTES.ADD_MUSALLI_MOSQUE_USER.title,
    component: AddEditMosqueProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 12,
    hideInSideBar: true,
    parentRouteName: ROUTES.MUSALLI_MOSQUE_MANAGEMENT.name,
    category: "MusalliManagement",
    subCategory: "Musalli",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_MUSALLI_MOSQUE_USER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_MUSALLI_MOSQUE_USER.name,
    displayName: ROUTES.EDIT_MUSALLI_MOSQUE_USER.title,
    component: AddEditMosqueProvider,
    isPrivate: true,
    icon: "setting",
    module: 12,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.MUSALLI_MOSQUE_MANAGEMENT.name,
    category: "MusalliManagement",
    subCategory: "Musalli",
    action: "Edit",
  },
  {
    path: ROUTES.MUSALLI_SESSION_MANAGEMENT.path,
    exact: true,
    name: ROUTES.MUSALLI_SESSION_MANAGEMENT.name,
    displayName: ROUTES.MUSALLI_SESSION_MANAGEMENT.title,
    component: MusalliSessionManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 12,
    category: "MusalliManagement",
    subCategory: "Musalli",
    action: "List",
  },
  {
    path: ROUTES.ADD_MUSALLI_SESSION_USER.path,
    exact: true,
    name: ROUTES.ADD_MUSALLI_SESSION_USER.name,
    displayName: ROUTES.ADD_MUSALLI_SESSION_USER.title,
    component: AddEditSessionProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 12,
    hideInSideBar: true,
    parentRouteName: ROUTES.MUSALLI_SESSION_MANAGEMENT.name,
    category: "MusalliManagement",
    subCategory: "Musalli",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_MUSALLI_SESSION_USER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_MUSALLI_SESSION_USER.name,
    displayName: ROUTES.EDIT_MUSALLI_SESSION_USER.title,
    component: AddEditSessionProvider,
    isPrivate: true,
    icon: "setting",
    module: 12,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.MUSALLI_SESSION_MANAGEMENT.name,
    category: "MusalliManagement",
    subCategory: "Musalli",
    action: "Edit",
  },
  {
    path: ROUTES.MUSALLI_PAYMENT_MANAGEMENT.path,
    exact: true,
    name: ROUTES.MUSALLI_PAYMENT_MANAGEMENT.name,
    displayName: ROUTES.MUSALLI_PAYMENT_MANAGEMENT.title,
    component: MusalliPaymentManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 12,
    category: "MusalliManagement",
    subCategory: "Musalli",
    action: "List",
  },
  {
    path: ROUTES.ADD_MUSALLI_PAYMENT_USER.path,
    exact: true,
    name: ROUTES.ADD_MUSALLI_PAYMENT_USER.name,
    displayName: ROUTES.ADD_MUSALLI_PAYMENT_USER.title,
    component: AddEditPaymentProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 12,
    hideInSideBar: true,
    parentRouteName: ROUTES.MUSALLI_PAYMENT_MANAGEMENT.name,
    category: "MusalliManagement",
    subCategory: "Musalli",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_MUSALLI_PAYMENT_USER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_MUSALLI_PAYMENT_USER.name,
    displayName: ROUTES.EDIT_MUSALLI_PAYMENT_USER.title,
    component: AddEditPaymentProvider,
    isPrivate: true,
    icon: "setting",
    module: 12,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.MUSALLI_PAYMENT_MANAGEMENT.name,
    category: "MusalliManagement",
    subCategory: "Musalli",
    action: "Edit",
  },

  // Baitussalam Web & App Management Routes

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_PROJECT_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_PROJECT_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_PROJECT_MANAGEMENT.title,
    component: BaitussalamWebAndAppProjectManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 13,
    category: "Web_AppManagement",
    subCategory: "Projects",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_PROJECT.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_PROJECT.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_PROJECT.title,
    component: AddEditBaitussalamWebAndAppProjectManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 13,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_PROJECT_MANAGEMENT.name,
    category: "Web_AppManagement",
    subCategory: "Projects",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PROJECT.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PROJECT.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PROJECT.title,
    component: AddEditBaitussalamWebAndAppProjectManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 13,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_PROJECT_MANAGEMENT.name,
    category: "Web_AppManagement",
    subCategory: "Projects",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_EVENTS_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_EVENTS_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_EVENTS_MANAGEMENT.title,
    component: BaitussalamWebAndAppEventManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 13,
    category: "Web_AppManagement",
    subCategory: "Events",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_PROJECT.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_PROJECT.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_PROJECT.title,
    component: AddEditBaitussalamWebAndAppEventManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 13,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_EVENTS_MANAGEMENT.name,
    category: "Web_AppManagement",
    subCategory: "Events",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PROJECT.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PROJECT.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PROJECT.title,
    component: AddEditBaitussalamWebAndAppEventManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 13,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_EVENTS_MANAGEMENT.name,
    category: "Web_AppManagement",
    subCategory: "Events",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_NAAT_COMPETITION_USER_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_NAAT_COMPETITION_USER_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_NAAT_COMPETITION_USER_MANAGEMENT.title,
    component: BaitussalamWebAndAppNaatUsersManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 14,
    category: "UsersManagement",
    subCategory: "Naat_Competition_Users",
    action: "List",
  },
  {
    path: `${ROUTES.BAITUSSALAM_WEB_AND_APP_NAAT_COMPETITION_USER_MANAGEMENT.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PROJECT.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PROJECT.title,
    component: AddEditBaitussalamWebAndAppNaatUsersManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 14,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_NAAT_COMPETITION_USER_MANAGEMENT.name,
    category: "UsersManagement",
    subCategory: "Naat_Competition_Users",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_GALLERIES_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_GALLERIES_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_GALLERIES_MANAGEMENT.title,
    component: BaitussalamWebAndAppGalleryManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 15,
    category: "ContentManagement",
    subCategory: "Galleries",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_GALLERIES.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_GALLERIES.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_GALLERIES.title,
    component: AddEditBaitussalamWebAndGalleryManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 15,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_GALLERIES_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Galleries",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_GALLERIES.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_GALLERIES.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_GALLERIES.title,
    component: AddEditBaitussalamWebAndGalleryManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 15,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_GALLERIES_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Galleries",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_NEWS_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_NEWS_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_NEWS_MANAGEMENT.title,
    component: BaitussalamWebAndAppNewsManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 13,
    category: "Web_AppManagement",
    subCategory: "News",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_NEWS.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_NEWS.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_NEWS.title,
    component: AddEditBaitussalamWebAndNewsManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 13,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_NEWS_MANAGEMENT.name,
    category: "Web_AppManagement",
    subCategory: "News",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_NEWS.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_NEWS.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_NEWS.title,
    component: AddEditBaitussalamWebAndNewsManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 13,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_NEWS_MANAGEMENT.name,
    category: "Web_AppManagement",
    subCategory: "News",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_BAYANAT_CATEGORY_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_BAYANAT_CATEGORY_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_BAYANAT_CATEGORY_MANAGEMENT.title,
    component: BaitussalamWebAndAppBayanatCategoryManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 15,
    category: "ContentManagement",
    subCategory: "Bayanat_Category",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_BAYANAT_CATEGORY.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_BAYANAT_CATEGORY.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_BAYANAT_CATEGORY.title,
    component: AddEditBaitussalamWebAndBayanatCategoryManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 15,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_BAYANAT_CATEGORY_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Bayanat_Category",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_BAYANAT_CATEGORY.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_BAYANAT_CATEGORY.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_BAYANAT_CATEGORY.title,
    component: AddEditBaitussalamWebAndBayanatCategoryManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 15,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_BAYANAT_CATEGORY_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Bayanat_Category",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_BAYANATS_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_BAYANATS_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_BAYANATS_MANAGEMENT.title,
    component: BaitussalamWebAndAppBayanaatManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 15,
    category: "ContentManagement",
    subCategory: "Bayanats",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_BAYANATS.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_BAYANATS.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_BAYANATS.title,
    component: AddEditBaitussalamWebAndBayanaatManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 15,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_BAYANATS_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Bayanats",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_BAYANATS.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_BAYANATS.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_BAYANATS.title,
    component: AddEditBaitussalamWebAndBayanaatManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 15,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_BAYANATS_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Bayanats",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_PUBLICATION_CATEGORY_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_PUBLICATION_CATEGORY_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_PUBLICATION_CATEGORY_MANAGEMENT.title,
    component: BaitussalamWebAndAppPublicationCategoryManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 15,
    category: "ContentManagement",
    subCategory: "Publication_Category",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_PUBLICATION_CATEGORY.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_PUBLICATION_CATEGORY.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_PUBLICATION_CATEGORY.title,
    component: AddEditBaitussalamWebAndPublicationCategoryManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 15,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_PUBLICATION_CATEGORY_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Publication_Category",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PUBLICATION_CATEGORY.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PUBLICATION_CATEGORY.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PUBLICATION_CATEGORY.title,
    component: AddEditBaitussalamWebAndPublicationCategoryManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 15,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_PUBLICATION_CATEGORY_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Publication_Category",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_PUBLICATIONS_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_PUBLICATIONS_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_PUBLICATIONS_MANAGEMENT.title,
    component: BaitussalamWebAndAppPublicationsManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 15,
    category: "ContentManagement",
    subCategory: "Publications",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_PUBLICATIONS.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_PUBLICATIONS.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_PUBLICATIONS.title,
    component: AddEditBaitussalamWebAndPublicationsManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 15,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_PUBLICATIONS_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Publications",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PUBLICATIONS.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PUBLICATIONS.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PUBLICATIONS.title,
    component: AddEditBaitussalamWebAndPublicationsManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 15,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_PUBLICATIONS_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Publications",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_GUIDES_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_GUIDES_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_GUIDES_MANAGEMENT.title,
    component: BaitussalamWebAndAppGuideManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 15,
    category: "ContentManagement",
    subCategory: "Guides",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_GUIDES.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_GUIDES.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_GUIDES.title,
    component: AddEditBaitussalamWebAndGuideManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 15,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_GUIDES_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Guides",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_GUIDES.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_GUIDES.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_GUIDES.title,
    component: AddEditBaitussalamWebAndGuideManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 15,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_GUIDES_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Guides",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_PARTNERS_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_PARTNERS_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_PARTNERS_MANAGEMENT.title,
    component: BaitussalamWebAndAppPartnerManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 13,
    category: "Web_AppManagement",
    subCategory: "Partners",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_PARTNERS.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_PARTNERS.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_PARTNERS.title,
    component: AddEditBaitussalamWebAndPartnerManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 13,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_PARTNERS_MANAGEMENT.name,
    category: "Web_AppManagement",
    subCategory: "Partners",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PARTNERS.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PARTNERS.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_PARTNERS.title,
    component: AddEditBaitussalamWebAndPartnerManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 13,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_PARTNERS_MANAGEMENT.name,
    category: "Web_AppManagement",
    subCategory: "Partners",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_NEWSLETTERS_SUBSCRIBE_USER_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_NEWSLETTERS_SUBSCRIBE_USER_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_NEWSLETTERS_SUBSCRIBE_USER_MANAGEMENT.title,
    component: BaitussalamWebAndNewslatterManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 14,
    category: "UsersManagement",
    subCategory: "Newsletters_Subscribe_Users",
    action: "List",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_ADMIN_USER_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_ADMIN_USER_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_ADMIN_USER_MANAGEMENT.title,
    component: BaitussalamWebAndAdminUsersManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 14,
    category: "UsersManagement",
    subCategory: "Admin_Users",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_ADMIN_USER.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_ADMIN_USER.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_ADMIN_USER.title,
    component: AddEditBaitussalamWebAndAdminUsersManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 14,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_ADMIN_USER_MANAGEMENT.name,
    category: "UsersManagement",
    subCategory: "Admin_Users",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_ADMIN_USER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_ADMIN_USER.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_ADMIN_USER.title,
    component: AddEditBaitussalamWebAndAdminUsersManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 14,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_ADMIN_USER_MANAGEMENT.name,
    category: "UsersManagement",
    subCategory: "Admin_Users",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_VOLUNTEERS_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_VOLUNTEERS_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_VOLUNTEERS_MANAGEMENT.title,
    component: BaitussalamWebAndVolunteerManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 14,
    category: "UsersManagement",
    subCategory: "Volunteers",
    action: "List",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_VOLUNTEERS.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_VOLUNTEERS.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_VOLUNTEERS.title,
    component: AddEditBaitussalamWebAndVolunteerManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 14,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_VOLUNTEERS_MANAGEMENT.name,
    category: "UsersManagement",
    subCategory: "Volunteers",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_VIDEOS_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_VIDEOS_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_VIDEOS_MANAGEMENT.title,
    component: BaitussalamWebAndVideoManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 15,
    category: "ContentManagement",
    subCategory: "Videos",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_VIDEOS.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_VIDEOS.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_VIDEOS.title,
    component: AddEditBaitussalamWebAndVideoManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 15,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_VIDEOS_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Videos",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_VIDEOS.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_VIDEOS.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_VIDEOS.title,
    component: AddEditBaitussalamWebAndVideoManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 15,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_VIDEOS_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Videos",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_DUA_CATEGORIES_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_DUA_CATEGORIES_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_DUA_CATEGORIES_MANAGEMENT.title,
    component: BaitussalamWebAndDuaCategoryManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 15,
    category: "ContentManagement",
    subCategory: "Dua_Categories",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_DUA_CATEGORIES.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_DUA_CATEGORIES.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_DUA_CATEGORIES.title,
    component: AddEditBaitussalamWebAndDuaCategoryManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 15,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_DUA_CATEGORIES_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Dua_Categories",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_DUA_CATEGORIES.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_DUA_CATEGORIES.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_DUA_CATEGORIES.title,
    component: AddEditBaitussalamWebAndDuaCategoryManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 15,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_DUA_CATEGORIES_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Dua_Categories",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_DUAS_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_DUAS_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_DUAS_MANAGEMENT.title,
    component: BaitussalamWebAndDuasManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 15,
    category: "ContentManagement",
    subCategory: "Duas",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_DUAS.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_DUAS.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_DUAS.title,
    component: AddEditBaitussalamWebAndDuasManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 15,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_DUAS_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Duas",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_DUAS.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_DUAS.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_DUAS.title,
    component: AddEditBaitussalamWebAndDuasManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 15,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_DUAS_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Duas",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_FEATURED_VIDEOS_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_FEATURED_VIDEOS_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_FEATURED_VIDEOS_MANAGEMENT.title,
    component: BaitussalamWebAndFeaturedVideoManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 15,
    category: "ContentManagement",
    subCategory: "Featured_Videos",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_FEATURED_VIDEOS.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_FEATURED_VIDEOS.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_FEATURED_VIDEOS.title,
    component: AddEditBaitussalamWebAndFeaturedVideoManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 15,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_FEATURED_VIDEOS_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Featured_Videos",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_FEATURED_VIDEOS.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_FEATURED_VIDEOS.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_FEATURED_VIDEOS.title,
    component: AddEditBaitussalamWebAndFeaturedVideoManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 15,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_FEATURED_VIDEOS_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Featured_Videos",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_FEATURED_BANNERS_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_FEATURED_BANNERS_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_FEATURED_BANNERS_MANAGEMENT.title,
    component: BaitussalamWebAndFeaturedBannerManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 15,
    category: "ContentManagement",
    subCategory: "Featured_Banners",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_FEATURED_BANNERS.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_FEATURED_BANNERS.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_FEATURED_BANNERS.title,
    component: AddEditBaitussalamWebAndFeaturedBannerManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 15,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_FEATURED_BANNERS_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Featured_Banners",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_FEATURED_BANNERS.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_FEATURED_BANNERS.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_FEATURED_BANNERS.title,
    component: AddEditBaitussalamWebAndFeaturedBannerManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 15,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_FEATURED_BANNERS_MANAGEMENT.name,
    category: "ContentManagement",
    subCategory: "Featured_Banners",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_ONLINE_CHARITIES_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_ONLINE_CHARITIES_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_ONLINE_CHARITIES_MANAGEMENT.title,
    component: BaitussalamWebAndOnlineCharityManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 13,
    category: "Web_AppManagement",
    subCategory: "Online_Charities",
    action: "List",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_ONLINE_CHARITIES.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_ONLINE_CHARITIES.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_ONLINE_CHARITIES.title,
    component: AddEditBaitussalamWebAndOnlineCharityManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 13,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_ONLINE_CHARITIES_MANAGEMENT.name,
    category: "Web_AppManagement",
    subCategory: "Online_Charities",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_DONATION_CATEGORIES_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_DONATION_CATEGORIES_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_DONATION_CATEGORIES_MANAGEMENT.title,
    component: BaitussalamWebAndDonationCategoryManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 13,
    category: "Web_AppManagement",
    subCategory: "Donation_Categories",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_DONATION_CATEGORIES.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_DONATION_CATEGORIES.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_DONATION_CATEGORIES.title,
    component: AddEditBaitussalamWebAndDonationCategoryManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 13,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_DONATION_CATEGORIES_MANAGEMENT.name,
    category: "Web_AppManagement",
    subCategory: "Donation_Categories",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_DONATION_CATEGORIES.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_DONATION_CATEGORIES.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_DONATION_CATEGORIES.title,
    component: AddEditBaitussalamWebAndDonationCategoryManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 13,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_DONATION_CATEGORIES_MANAGEMENT.name,
    category: "Web_AppManagement",
    subCategory: "Donation_Categories",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_CUSTOMERS_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_CUSTOMERS_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_CUSTOMERS_MANAGEMENT.title,
    component: BaitussalamWebAndDonationCustomerManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 14,
    category: "UsersManagement",
    subCategory: "Customers",
    action: "List",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_CUSTOMERS.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_CUSTOMERS.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_CUSTOMERS.title,
    component: AddEditBaitussalamWebAndDonationCustomerManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 14,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_CUSTOMERS_MANAGEMENT.name,
    category: "UsersManagement",
    subCategory: "Customers",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_HIJRI_DATES_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_HIJRI_DATES_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_HIJRI_DATES_MANAGEMENT.title,
    component: BaitussalamWebAndHijriDateManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 13,
    category: "Web_AppManagement",
    subCategory: "Hijri_Dates",
    action: "List",
  },
  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_SAIBAN_SUBMISSIONS_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_SAIBAN_SUBMISSIONS_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_SAIBAN_SUBMISSIONS_MANAGEMENT.title,
    component: BaitussalamWebAndSaibanManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 14,
    category: "UsersManagement",
    subCategory: "Saiban_Submissions",
    action: "List",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_SAIBAN_SUBMISSIONS.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_SAIBAN_SUBMISSIONS.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_SAIBAN_SUBMISSIONS.title,
    component: AddEditBaitussalamWebAndSaibanManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 14,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_SAIBAN_SUBMISSIONS_MANAGEMENT.name,
    category: "UsersManagement",
    subCategory: "Saiban_Submissions",
    action: "Edit",
  },

  {
    path: ROUTES.BAITUSSALAM_WEB_AND_APP_SETTINGS_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BAITUSSALAM_WEB_AND_APP_SETTINGS_MANAGEMENT.name,
    displayName: ROUTES.BAITUSSALAM_WEB_AND_APP_SETTINGS_MANAGEMENT.title,
    component: BaitussalamWebAndSettingManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 13,
    category: "Web_AppManagement",
    subCategory: "Settings",
    action: "List",
  },
  {
    path: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_SETTINGS.path,
    exact: true,
    name: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_SETTINGS.name,
    displayName: ROUTES.ADD_BAITUSSALAM_WEB_AND_APP_SETTINGS.title,
    component: AddEditBaitussalamWebAndSettingManagementProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: false,
    module: 13,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_SETTINGS_MANAGEMENT.name,
    category: "Web_AppManagement",
    subCategory: "Settings",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_SETTINGS.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_SETTINGS.name,
    displayName: ROUTES.EDIT_BAITUSSALAM_WEB_AND_APP_SETTINGS.title,
    component: AddEditBaitussalamWebAndSettingManagementProvider,
    isPrivate: true,
    icon: "setting",
    module: 13,
    isHiddenInMenu: false,
    hideInSideBar: true,
    parentRouteName: ROUTES.BAITUSSALAM_WEB_AND_APP_SETTINGS_MANAGEMENT.name,
    category: "Web_AppManagement",
    subCategory: "Settings",
    action: "Edit",
  }

];

export default routes;
