import React from "react";
import CreateVoucherTicket from "../components/CreateVoucherTicket/CreateVoucherTicket";
import BookActivationReport from "../containers/BookActivationReport/BookActivationReport";
import BookOrderReport from "../containers/BookOrderReports/BookOrderReports";
import ConsumerReports from "../containers/ConsumerReport/ConsumerReport";
import SalesReport from "../containers/SalesReports/SalesReports";
import UserLoginReport from "../containers/UserLoginReport";
import VoucherRedemptionReport from "../containers/VoucherRedemptionReport/VoucherRedemptionReport";
import AddEditBookPurchaseProvider from "../providers/AddEditBookPurchaseRequest.provider";
import AddEditBookSubscriptionProvider from "../providers/addEditBookSubscription.provider";
import AddEditBrandProvider from "../providers/addEditBrand.provider";
import AddEditItemProvider from "../providers/addEditItem.provider";
import AdminManagementProvider from "../providers/adminManagement.provider";
import AreaSegmentProvider from "../providers/areaSegment.provider";
import BookManagementProvider from "../providers/bookManagement.provider";
import BookOrderManagementProvider from "../providers/bookOrderManagement.provider";
import BookSubscriptionManagementProvider from "../providers/bookSubscriptionManagement.provider";
import BrandManagementProvider from "../providers/brandManagement.provider";
import CampaignDesignerProvider from "../providers/campaignDesigner.provider";
import ConsumerManagementProvider from "../providers/consumerManagement.provider";
import CorporateCustomerManagementProvider from "../providers/corporateCustomerManagement.provider";
import DealCategoryManagementProvider from "../providers/dealCategoryManagement.provider";
import DealManagementProvider from "../providers/dealManagement.provider";
import LandingPageDesignerProvider from "../providers/landingPageDesigner.provider";
import LandingPageManagementProvider from "../providers/landingPageManagement.provider";
import MerchantManagementProvider from "../providers/merchantManagement.provider";
import OutletBillingManagementProvider from "../providers/outletBIllingManagementProvider";
import PartnerManagementProvider from "../providers/partnerManagement.provider";
import SessionManagementProvider from "../providers/SessionManagment.provider";
import VoucherRedemptionManagementProvider from "../providers/VoucherRedemptionManagement.provider";
import ROUTES from "./constant.route";

const ChangePasswordProvider = React.lazy(() => import("../providers/changePassword.provider"));

const BookOrderReportsProvider = React.lazy(() => import("../providers/bookOrderPurchaseReports.provider"));
const DashboardProvider = React.lazy(() => import("../providers/dashboard.provider"));
const MerchantDashboardProvider = React.lazy(() => import("../providers/merchantDashboard.provider"));

const ProfileProvider = React.lazy(() => import("../providers/profile.provider"));

const AddEditDealProvider = React.lazy(() => import("../providers/addEditDeal.provider"));
const AddEditCorporateCustomerProvider = React.lazy(() => import("../providers/addEditCorporateCustomer.provider"));
const AddEditPartnerProvider = React.lazy(() => import("../providers/addEditPartner.provider"));
const ViewPartnerProvider = React.lazy(() => import("../providers/viewPartner.provider"));
const PartnerProfileProvider = React.lazy(() => import("../providers/partnerProfile.provider"));
const AddEditCampaignProvider = React.lazy(() => import("../providers/addEditCampaign.provider"));
const SwimLaneManagerProvider = React.lazy(() => import("../providers/swimLaneManager.provider"));
// const AddAreaSegmentProvider=React.lazy(()=>import("../providers/addAreaSegmentManagement.provider"))
// const EditAreaSegmentProvider=React.lazy(()=>import("../providers/editAreaSegmentManagement.provider"))

const AddEditAreaSegmentProvider = React.lazy(() => import("../providers/addEditAreaSegment.provider"));

const AddEditBookProvider = React.lazy(() => import("../providers/addEditBookManagement.provider"));
const AddEditProfilerProvider = React.lazy(() => import("../providers/addEditProfiler.provider"));

// const AddAdminUserProvider = React.lazy(() => import("../providers/addAdmin.provider"));
// const EditAdminUserProvider = React.lazy(() => import("../providers/editAdmin.provider"));

const AddEditAdminProvider = React.lazy(() => import("../providers/addEditAdmin.provider"));

const AddEditConsumerProvider = React.lazy(() => import("../providers/addEditConsumer.provider"));

const AddEditDealCategoryProvider = React.lazy(() => import("../providers/addEditDealCategory.provider"));

const campaignStatusConsoleProvider = React.lazy(() => import("../providers/campaignStatusConsole.provider"));
const ViewCampaignStatisticsProvider = React.lazy(() => import("../providers/viewCampaignStatistics.provider"));

const AddEditMerchantUserProvider = React.lazy(() => import("../providers/addEditMerchant.provider"));
const MerchantProfileProvider = React.lazy(() => import("../providers/merchantProfile.provider"));
const AddEditVoucherRedemptionProvider = React.lazy(() => import("../providers/addEditVoucherRedemption.provider"));

// Home

// User Management
//   Admin Management
//   Merchant Management
//   Consumer Management

// Partner Management
//   Area Segment Management
//   Brand Management
//   Partner Management

// Deal Management
//   Category Management
//   Deal Management
//   Book Management
//   Campaign Management
//   Books Purchase Requests

// Reports
//   Deal Redeem Reports
//   Book Purchase Reports
//   Campaign Reports

const routes = [
  {
    path: `${ROUTES.CHANGE_PASSWORD.path}/:id`,
    exact: true,
    name: ROUTES.CHANGE_PASSWORD.name,
    displayName: ROUTES.CHANGE_PASSWORD.title,
    component: ChangePasswordProvider,
    isPrivate: true,
    icon: "HomeOutlined",
    isHiddenInMenu: true,
    hideInSideBar: true,
    module: 0,
    category: "ChangePassword",
    action: "View",
  },
  {
    path: ROUTES.DASHBOARD.path,
    exact: true,
    name: ROUTES.DASHBOARD.name,
    displayName: ROUTES.DASHBOARD.title,
    component: DashboardProvider,
    isPrivate: true,
    icon: "HomeOutlined",
    isDisabled: false,
    module: 0,
    category: "Home",
    action: "View",
  },
  {
    path: ROUTES.PROFILE.path,
    exact: true,
    name: ROUTES.PROFILE.name,
    displayName: ROUTES.PROFILE.title,
    component: ProfileProvider,
    isPrivate: true,
    icon: "ProfileOutlined",
    isHiddenInMenu: true,
    module: 0,
    category: "Profile",
    action: "View",
  },
  {
    path: ROUTES.SESSION_MANAGEMENT.path,
    exact: true,
    name: ROUTES.SESSION_MANAGEMENT.name,
    displayName: ROUTES.SESSION_MANAGEMENT.title,
    component: SessionManagementProvider,
    isPrivate: true,
    icon: "SmileOutlined",
    isDisabled: false,
    module: 1,
    category: "UserManagement",
    subCategory: "Session",
    action: "List",
  },
  {
    path: ROUTES.ADMIN_MANAGEMENT.path,
    exact: true,
    name: ROUTES.ADMIN_MANAGEMENT.name,
    displayName: ROUTES.ADMIN_MANAGEMENT.title,
    component: AdminManagementProvider,
    isPrivate: true,
    icon: "HeartOutlined",
    module: 1,
    category: "UserManagement",
    subCategory: "Admin",
    action: "List",
  },
  {
    path: ROUTES.ADD_ADMIN_USER.path,
    exact: true,
    name: ROUTES.ADD_ADMIN_USER.name,
    displayName: ROUTES.ADD_ADMIN_USER.title,
    component: AddEditAdminProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: true,
    module: 0,
    hideInSideBar: true,
    parentRouteName: ROUTES.ADMIN_MANAGEMENT.name,
    category: "UserManagement",
    subCategory: "Admin",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_ADMIN_USER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_ADMIN_USER.name,
    displayName: ROUTES.EDIT_ADMIN_USER.title,
    component: AddEditAdminProvider,
    isPrivate: true,
    icon: "setting",
    module: 0,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.ADMIN_MANAGEMENT.name,
    category: "UserManagement",
    subCategory: "Admin",
    action: "Edit",
  },
  {
    path: ROUTES.MERCHANT_MANAGEMENT.path,
    exact: true,
    name: ROUTES.MERCHANT_MANAGEMENT.name,
    displayName: ROUTES.MERCHANT_MANAGEMENT.title,
    component: MerchantManagementProvider,
    isPrivate: true,
    icon: "StarOutlined",
    isDisabled: false,
    module: 1,
    category: "UserManagement",
    subCategory: "Merchant",
    action: "List",
  },
  {
    path: ROUTES.ADD_MERCHANT_USER.path,
    exact: true,
    name: ROUTES.ADD_MERCHANT_USER.name,
    displayName: ROUTES.ADD_MERCHANT_USER.title,
    component: AddEditMerchantUserProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: true,
    module: 0,
    hideInSideBar: true,
    parentRouteName: ROUTES.MERCHANT_MANAGEMENT.name,
    category: "UserManagement",
    subCategory: "Merchant",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_MERCHANT_USER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_MERCHANT_USER.name,
    displayName: ROUTES.EDIT_MERCHANT_USER.title,
    component: AddEditMerchantUserProvider,
    isPrivate: true,
    icon: "setting",
    module: 0,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.MERCHANT_MANAGEMENT.name,
    category: "UserManagement",
    subCategory: "Merchant",
    action: "Edit",
  },
  {
    path: `${ROUTES.MERCHANT_PROFILE.path}`,
    exact: true,
    name: ROUTES.MERCHANT_PROFILE.name,
    displayName: ROUTES.MERCHANT_PROFILE.title,
    component: MerchantProfileProvider,
    isPrivate: true,
    icon: "setting",
    module: 0,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.MERCHANT_MANAGEMENT.name,
    category: "UserManagement",
    subCategory: "Merchant",
    action: "Profile",
  },
  {
    path: ROUTES.CONSUMER_MANAGEMENT.path,
    exact: true,
    name: ROUTES.CONSUMER_MANAGEMENT.name,
    displayName: ROUTES.CONSUMER_MANAGEMENT.title,
    component: ConsumerManagementProvider,
    isPrivate: true,
    icon: "AccountBookOutlined",
    module: 1,
    category: "UserManagement",
    subCategory: "Consumer",
    action: "List",
  },
  {
    path: ROUTES.ADD_CONSUMER_USER.path,
    exact: true,
    name: ROUTES.ADD_CONSUMER_USER.name,
    displayName: ROUTES.ADD_CONSUMER_USER.title,
    component: AddEditConsumerProvider,
    isPrivate: true,
    icon: "user",
    isHiddenInMenu: true,
    hideInSideBar: true,
    module: 1,
    parentRouteName: ROUTES.CONSUMER_MANAGEMENT.name,
    category: "UserManagement",
    subCategory: "Consumer",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_CONSUMER_USER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_CONSUMER_USER.name,
    displayName: ROUTES.EDIT_CONSUMER_USER.title,
    component: AddEditConsumerProvider,
    isPrivate: true,
    icon: "user",
    isHiddenInMenu: true,
    hideInSideBar: true,
    module: 1,
    parentRouteName: ROUTES.CONSUMER_MANAGEMENT.name,
    category: "UserManagement",
    subCategory: "Consumer",
    action: "Edit",
  },
  {
    path: ROUTES.AREA_SEGMENT_MANAGEMENT.path,
    exact: true,
    name: ROUTES.AREA_SEGMENT_MANAGEMENT.name,
    displayName: ROUTES.AREA_SEGMENT_MANAGEMENT.title,
    component: AreaSegmentProvider,
    isPrivate: true,
    icon: "PushpinOutlined",
    module: 2,
    category: "PartnerManagement",
    subCategory: "AreaSegment",
    action: "List",
  },
  {
    path: ROUTES.ADD_PARTNER.path,
    exact: true,
    name: ROUTES.ADD_PARTNER.name,
    displayName: ROUTES.ADD_PARTNER.title,
    component: AddEditPartnerProvider,
    isPrivate: true,
    icon: "team",
    isHiddenInMenu: true,
    module: 2,
    hideInSideBar: true,
    parentRouteName: ROUTES.PARTNER_MANAGEMENT.name,
    category: "PartnerManagement",
    subCategory: "Partner",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_PARTNER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_PARTNER.name,
    displayName: ROUTES.EDIT_PARTNER.title,
    component: AddEditPartnerProvider,
    isPrivate: true,
    icon: "team",
    isHiddenInMenu: true,
    module: 2,
    hideInSideBar: true,
    parentRouteName: ROUTES.PARTNER_MANAGEMENT.name,
    category: "PartnerManagement",
    subCategory: "Partner",
    action: "Edit",
  },
  {
    path: `${ROUTES.VIEW_PARTNER.path}/:id`,
    exact: true,
    name: ROUTES.VIEW_PARTNER.name,
    displayName: ROUTES.VIEW_PARTNER.title,
    component: ViewPartnerProvider,
    isPrivate: true,
    icon: "team",
    isHiddenInMenu: true,
    module: 2,
    hideInSideBar: true,
    parentRouteName: ROUTES.PARTNER_MANAGEMENT.name,
    category: "PartnerManagement",
    subCategory: "Partner",
    action: "View",
  },
  {
    path: `${ROUTES.PARTNER_PROFILE.path}`,
    exact: true,
    name: ROUTES.PARTNER_PROFILE.name,
    displayName: ROUTES.PARTNER_PROFILE.title,
    component: PartnerProfileProvider,
    isPrivate: true,
    icon: "team",
    isHiddenInMenu: true,
    module: 2,
    hideInSideBar: true,
    parentRouteName: ROUTES.PARTNER_MANAGEMENT.name,
    category: "PartnerManagement",
    subCategory: "Partner",
    action: "Profile",
  },

  {
    path: ROUTES.BRAND_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BRAND_MANAGEMENT.name,
    displayName: ROUTES.BRAND_MANAGEMENT.title,
    component: BrandManagementProvider,
    isPrivate: true,
    icon: "MoneyCollectOutlined",
    module: 2,
    category: "PartnerManagement",
    subCategory: "Brand",
    action: "List",
  },

  {
    path: ROUTES.ADD_AREA_SEGMENT.path,
    exact: true,
    name: ROUTES.ADD_AREA_SEGMENT.name,
    displayName: ROUTES.ADD_AREA_SEGMENT.title,
    component: AddEditAreaSegmentProvider,
    isPrivate: true,
    icon: "environment",
    module: 2,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.AREA_SEGMENT_MANAGEMENT.name,
    category: "PartnerManagement",
    subCategory: "AreaSegment",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_AREA_SEGMENT.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_AREA_SEGMENT.name,
    displayName: ROUTES.EDIT_AREA_SEGMENT.title,
    component: AddEditAreaSegmentProvider,
    isPrivate: true,
    icon: "environment",
    module: 2,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.AREA_SEGMENT_MANAGEMENT.name,
    category: "PartnerManagement",
    subCategory: "AreaSegment",
    action: "Edit",
  },
  {
    path: ROUTES.PARTNER_MANAGEMENT.path,
    exact: true,
    name: ROUTES.PARTNER_MANAGEMENT.name,
    displayName: ROUTES.PARTNER_MANAGEMENT.title,
    component: PartnerManagementProvider,
    isPrivate: true,
    icon: "MobileOutlined",
    module: 2,
    category: "PartnerManagement",
    subCategory: "Partner",
    action: "List",
  },
  {
    path: `${ROUTES.EDIT_BRAND.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BRAND.name,
    displayName: ROUTES.EDIT_BRAND.title,
    component: AddEditBrandProvider,
    isPrivate: true,
    isHiddenInMenu: true,
    hideInSideBar: true,
    icon: "barcode",
    module: 2,
    category: "PartnerManagement",
    subCategory: "Brand",
    action: "Edit",
  },
  {
    path: ROUTES.ADD_BRAND.path,
    exact: true,
    name: ROUTES.ADD_BRAND.name,
    displayName: ROUTES.ADD_BRAND.title,
    component: AddEditBrandProvider,
    isPrivate: true,
    isHiddenInMenu: true,
    hideInSideBar: true,
    icon: "barcode",
    module: 2,
    category: "PartnerManagement",
    subCategory: "Brand",
    action: "Add",
  },
  {
    path: ROUTES.CATEGORY_MANAGEMENT.path,
    exact: true,
    name: ROUTES.CATEGORY_MANAGEMENT.name,
    displayName: ROUTES.CATEGORY_MANAGEMENT.title,
    component: DealCategoryManagementProvider,
    isPrivate: true,
    icon: "DollarOutlined",
    module: 3,
    category: "VoucherManagement",
    subCategory: "Category",
    action: "List",
  },
  {
    path: ROUTES.ADD_DEAL.path,
    exact: true,
    name: ROUTES.ADD_DEAL.name,
    displayName: ROUTES.ADD_DEAL.title,
    component: AddEditDealProvider,
    isPrivate: true,
    icon: "user",
    isHiddenInMenu: true,
    hideInSideBar: true,
    module: 3,
    parentRouteName: ROUTES.DEAL_MANAGEMENT.name,
    category: "VoucherManagement",
    subCategory: "Voucher",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_DEAL.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_DEAL.name,
    displayName: ROUTES.EDIT_DEAL.title,
    component: AddEditDealProvider,
    isPrivate: true,
    icon: "user",
    isHiddenInMenu: true,
    hideInSideBar: true,
    module: 3,
    parentRouteName: ROUTES.DEAL_MANAGEMENT.name,
    category: "VoucherManagement",
    subCategory: "Voucher",
    action: "Edit",
  },

  {
    path: ROUTES.DEAL_MANAGEMENT.path,
    exact: true,
    name: ROUTES.DEAL_MANAGEMENT.name,
    displayName: ROUTES.DEAL_MANAGEMENT.title,
    component: DealManagementProvider,
    isPrivate: true,
    icon: "AccountBookOutlined",
    module: 3,
    category: "VoucherManagement",
    subCategory: "Voucher",
    action: "List",
  },

  {
    path: ROUTES.ADD_CATEGORY.path,
    exact: true,
    name: ROUTES.ADD_CATEGORY.name,
    displayName: ROUTES.ADD_CATEGORY.title,
    component: AddEditDealCategoryProvider,
    isPrivate: true,
    icon: "user",
    isHiddenInMenu: true,
    hideInSideBar: true,
    module: 1,
    parentRouteName: ROUTES.CATEGORY_MANAGEMENT.name,
    category: "VoucherManagement",
    subCategory: "Category",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_CATEGORY.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_CATEGORY.name,
    displayName: ROUTES.EDIT_CATEGORY.title,
    component: AddEditDealCategoryProvider,
    isPrivate: true,
    icon: "user",
    isHiddenInMenu: true,
    hideInSideBar: true,
    module: 1,
    parentRouteName: ROUTES.CATEGORY_MANAGEMENT.name,
    category: "VoucherManagement",
    subCategory: "Category",
    action: "Edit",
  },
  {
    path: ROUTES.BOOK_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BOOK_MANAGEMENT.name,
    displayName: ROUTES.BOOK_MANAGEMENT.title,
    component: BookManagementProvider,
    isPrivate: true,
    icon: "BookOutlined",
    module: 3,
    category: "VoucherManagement",
    subCategory: "Book",
    action: "List",
  },
  {
    path: ROUTES.ADD_BOOK.path,
    exact: true,
    name: ROUTES.ADD_BOOK.name,
    displayName: ROUTES.ADD_BOOK.title,
    component: AddEditBookProvider,
    isPrivate: true,
    icon: "book",
    module: 3,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.BOOK_MANAGEMENT.name,
    category: "VoucherManagement",
    subCategory: "Book",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BOOK.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_BOOK.name,
    displayName: ROUTES.EDIT_BOOK.title,
    component: AddEditBookProvider,
    isPrivate: true,
    icon: "book",
    module: 3,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.BOOK_MANAGEMENT.name,
    category: "VoucherManagement",
    subCategory: "Book",
    action: "Edit",
  },

  {
    path: ROUTES.BOOK_PURCHASE_REQUESTS.path,
    exact: true,
    name: ROUTES.BOOK_PURCHASE_REQUESTS.name,
    displayName: ROUTES.BOOK_PURCHASE_REQUESTS.title,
    component: () => ROUTES.BOOK_PURCHASE_REQUESTS.title,
    isPrivate: true,
    icon: "BookOutlined",
    module: 3,
    category: "VoucherManagement",
    subCategory: "BookPurchaseRequest",
    action: "List",
  },
  {
    path: ROUTES.BOOK_ORDERS.path,
    exact: true,
    name: ROUTES.BOOK_ORDERS.name,
    displayName: ROUTES.BOOK_ORDERS.title,
    component: BookOrderManagementProvider,
    isPrivate: true,
    icon: "MobileOutlined",
    module: 4,
    category: "BookSubscriptionManagement",
    subCategory: "BookOrderManagement",
    action: "List",
  },
  {
    path: ROUTES.NEW_REQUEST.path,
    exact: true,
    name: ROUTES.NEW_REQUEST.name,
    displayName: ROUTES.NEW_REQUEST.title,
    component: AddEditBookPurchaseProvider,
    isPrivate: true,
    hideInSideBar: true,
    icon: "solution",
    module: 4,
    category: "BookSubscriptionManagement",
    subCategory: "BookOrderManagement",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_NEW_REQUEST.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_NEW_REQUEST.name,
    displayName: ROUTES.EDIT_NEW_REQUEST.title,
    component: AddEditBookPurchaseProvider,
    isPrivate: true,
    hideInSideBar: true,
    icon: "solution",
    module: 4,
    category: "BookSubscriptionManagement",
    subCategory: "BookOrderManagement",
    action: "Edit",
  },
  {
    path: ROUTES.CORPORATE_CUSTOMER_MANAGEMENT.path,
    exact: true,
    name: ROUTES.CORPORATE_CUSTOMER_MANAGEMENT.name,
    displayName: ROUTES.CORPORATE_CUSTOMER_MANAGEMENT.title,
    component: CorporateCustomerManagementProvider,
    isPrivate: true,
    icon: "StarOutlined",
    module: 4,
    category: "BookSubscriptionManagement",
    subCategory: "CorporateCustomer",
    action: "List",
  },
  {
    path: ROUTES.ADD_CORPORATE_CUSTOMER.path,
    exact: true,
    name: ROUTES.ADD_CORPORATE_CUSTOMER.name,
    displayName: ROUTES.ADD_CONSUMER_USER.title,
    component: AddEditCorporateCustomerProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: true,
    module: 4,
    hideInSideBar: true,
    parentRouteName: ROUTES.CORPORATE_CUSTOMER_MANAGEMENT.name,
    category: "BookSubscriptionManagement",
    subCategory: "CorporateCustomer",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_CORPORATE_CUSTOMER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_CORPORATE_CUSTOMER.name,
    displayName: ROUTES.EDIT_CORPORATE_CUSTOMER.title,
    component: AddEditCorporateCustomerProvider,
    isPrivate: true,
    icon: "setting",
    isHiddenInMenu: true,
    module: 4,
    hideInSideBar: true,
    parentRouteName: ROUTES.CORPORATE_CUSTOMER_MANAGEMENT.name,
    category: "BookSubscriptionManagement",
    subCategory: "CorporateCustomer",
    action: "Edit",
  },
  {
    path: ROUTES.BOOK_SUBSCRIPTION_MANAGEMENT.path,
    exact: true,
    name: ROUTES.BOOK_SUBSCRIPTION_MANAGEMENT.name,
    displayName: ROUTES.BOOK_SUBSCRIPTION_MANAGEMENT.title,
    component: BookSubscriptionManagementProvider,
    isPrivate: true,
    icon: "solution",
    module: 4,
    category: "BookSubscriptionManagement",
    subCategory: "BookSubscription",
    action: "List",
  },
  {
    path: ROUTES.ADD_BOOK_SUBSCRIPTION.path,
    exact: true,
    name: ROUTES.ADD_BOOK_SUBSCRIPTION.name,
    parentRouteName: ROUTES.BOOK_SUBSCRIPTION_MANAGEMENT.name,
    displayName: ROUTES.ADD_BOOK_SUBSCRIPTION.title,
    component: AddEditBookSubscriptionProvider,
    isPrivate: true,
    hideInSideBar: true,
    icon: "solution",
    module: 4,
    category: "BookSubscriptionManagement",
    subCategory: "BookSubscription",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_BOOK_SUBSCRIPTION.path}/:id`,
    exact: true,
    name: ROUTES.ADD_BOOK_SUBSCRIPTION.name,
    parentRouteName: ROUTES.BOOK_SUBSCRIPTION_MANAGEMENT.name,
    displayName: ROUTES.ADD_BOOK_SUBSCRIPTION.title,
    component: AddEditBookSubscriptionProvider,
    isPrivate: true,
    hideInSideBar: true,
    icon: "solution",
    module: 4,
    category: "BookSubscriptionManagement",
    subCategory: "BookSubscription",
    action: "Edit",
  },
  {
    path: ROUTES.VOUCHER_REDEMPTION_MANAGEMENT.path,
    exact: true,
    name: ROUTES.VOUCHER_REDEMPTION_MANAGEMENT.name,
    displayName: ROUTES.VOUCHER_REDEMPTION_MANAGEMENT.title,
    component: VoucherRedemptionManagementProvider,
    isPrivate: true,
    icon: "tags",
    module: 11,
    category: "VoucherRedemptionManagement",
    subCategory: "VoucherRedemption",
    action: "List",
  },
  {
    path: ROUTES.ADD_VOUCHER_REDEMPTION.path,
    exact: true,
    name: ROUTES.ADD_VOUCHER_REDEMPTION.name,
    displayName: ROUTES.ADD_VOUCHER_REDEMPTION.title,
    component: CreateVoucherTicket,
    isPrivate: true,
    hideInSideBar: false,
    parentRouteName: ROUTES.VOUCHER_REDEMPTION_MANAGEMENT.name,
    icon: "tags",
    module: 11,
    category: "VoucherRedemptionManagement",
    subCategory: "VoucherRedemption",
    action: "Add",
  },
  {
    path: ROUTES.MERCHANT_DASHBOARD.path,
    exact: true,
    name: ROUTES.MERCHANT_DASHBOARD.name,
    displayName: ROUTES.MERCHANT_DASHBOARD.title,
    component: MerchantDashboardProvider,
    isPrivate: true,
    icon: "HomeOutlined",
    isDisabled: false,
    module: 5,
    category: "MerchantHome",
    action: "View",
  },
  {
    path: `${ROUTES.EDIT_VOUCHER_REDEMPTION.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_VOUCHER_REDEMPTION.name,
    displayName: ROUTES.EDIT_VOUCHER_REDEMPTION.title,
    component: AddEditVoucherRedemptionProvider,
    isPrivate: true,
    hideInSideBar: true,
    icon: "tags",
    module: 11,
    category: "VoucherRedemptionManagement",
    subCategory: "VoucherRedemption",
    action: "Edit",
  },
  {
    path: ROUTES.CAMPAIGN_DESIGNER.path,
    exact: true,
    name: ROUTES.CAMPAIGN_DESIGNER.name,
    displayName: ROUTES.CAMPAIGN_DESIGNER.title,
    component: CampaignDesignerProvider,
    isPrivate: true,
    icon: "StarOutlined",
    module: 6,
    category: "PromotionManagement",
    subCategory: "CampaignDesigner",
    action: "List",
  },
  {
    path: `${ROUTES.CAMPAIGN_STATUS_VIEW.path}/:id`,
    exact: true,
    name: ROUTES.CAMPAIGN_STATUS_VIEW.name,
    displayName: ROUTES.CAMPAIGN_STATUS_VIEW.title,
    component: ViewCampaignStatisticsProvider,
    parentRouteName: ROUTES.CAMPAIGN_STATUS_VIEW.name,
    isPrivate: true,
    hideInSideBar: true,
    icon: "tags",
    module: 6,
    category: "PromotionManagement",
    subCategory: "CampaignStatus",
    action: "View",
  },
  {
    path: ROUTES.CAMPAIGN_STATUS.path,
    exact: true,
    name: ROUTES.CAMPAIGN_STATUS.name,
    displayName: ROUTES.CAMPAIGN_STATUS.title,
    component: campaignStatusConsoleProvider,
    isPrivate: true,
    icon: "tags",
    module: 6,
    category: "PromotionManagement",
    subCategory: "CampaignStatus",
    action: "List",
  },
  {
    path: ROUTES.ADD_CAMPAIGN.path,
    exact: true,
    name: ROUTES.ADD_CAMPAIGN.name,
    displayName: ROUTES.ADD_CAMPAIGN.title,
    component: AddEditCampaignProvider,
    isPrivate: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.CAMPAIGN_DESIGNER.name,
    icon: "StarOutlined",
    module: 6,
    category: "PromotionManagement",
    subCategory: "CampaignDesigner",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_CAMPAIGN.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_CAMPAIGN.name,
    displayName: ROUTES.EDIT_CAMPAIGN.title,
    component: AddEditCampaignProvider,
    isPrivate: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.CAMPAIGN_DESIGNER.name,
    icon: "StarOutlined",
    module: 6,
    category: "PromotionManagement",
    subCategory: "CampaignDesigner",
    action: "Edit",
  },
  {
    path: ROUTES.BOOK_ORDER_REPORT.path,
    exact: true,
    name: ROUTES.BOOK_ORDER_REPORT.name,
    displayName: ROUTES.BOOK_ORDER_REPORT.title,
    component: BookOrderReport,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 10,
    category: "ReportsManagement",
    subCategory: "BookOrderReport",
    action: "List",
  },
  {
    path: ROUTES.BOOK_ACTIVATION_REPORT.path,
    exact: true,
    name: ROUTES.BOOK_ACTIVATION_REPORT.name,
    displayName: ROUTES.BOOK_ACTIVATION_REPORT.title,
    component: BookActivationReport,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 10,
    category: "ReportsManagement",
    subCategory: "BookActivationReport",
    action: "List",
  },
  {
    path: ROUTES.VOUCHER_REDEMPTION_REPORT.path,
    exact: true,
    name: ROUTES.VOUCHER_REDEMPTION_REPORT.name,
    displayName: ROUTES.VOUCHER_REDEMPTION_REPORT.title,
    component: VoucherRedemptionReport,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 10,
    category: "ReportsManagement",
    subCategory: "VoucherRedemptionReport",
    action: "List",
  },
  {
    path: ROUTES.SALES_REPORT.path,
    exact: true,
    name: ROUTES.SALES_REPORT.name,
    displayName: ROUTES.SALES_REPORT.title,
    component: SalesReport,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 10,
    category: "ReportsManagement",
    subCategory: "SalesReport",
    action: "List",
  },
  {
    path: ROUTES.CONSUMER_REPORT.path,
    exact: true,
    name: ROUTES.CONSUMER_REPORT.name,
    displayName: ROUTES.CONSUMER_REPORT.title,
    component: ConsumerReports,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 10,
    category: "ReportsManagement",
    subCategory: "ConsumerReports",
    action: "List",
  },
  {
    path: ROUTES.USER_LOGIN_REPORT.path,
    exact: true,
    name: ROUTES.USER_LOGIN_REPORT.name,
    displayName: ROUTES.USER_LOGIN_REPORT.title,
    component: UserLoginReport,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 10,
    category: "ReportsManagement",
    subCategory: "UserLoginReport",
    action: "List",
  },
  // {
  //   path: ROUTES.DEAL_REDEEM_REPORTS.path,
  //   exact: true,
  //   name: ROUTES.DEAL_REDEEM_REPORTS.name,
  //   displayName: ROUTES.DEAL_REDEEM_REPORTS.title,
  //   component: () => ROUTES.DEAL_REDEEM_REPORTS.title,
  //   isPrivate: true,
  //   icon: "BarChartOutlined",
  //   module: 10,
  //   category: "ReportsManagement",
  //   subCategory: "DealRedeem",
  //   action: "List",
  // },
  // {
  //   path: ROUTES.BOOK_PURCHASE_REPORT.path,
  //   exact: true,
  //   name: ROUTES.BOOK_PURCHASE_REPORT.name,
  //   displayName: ROUTES.BOOK_PURCHASE_REPORT.title,
  //   component: BookOrderReportsProvider,
  //   isPrivate: true,
  //   icon: "BarChartOutlined",
  //   module: 10,
  //   category: "ReportsManagement",
  //   subCategory: "BookPurchase",
  //   action: "List",
  // },
  // {
  //   path: ROUTES.CAMPAIGN_REPORT.path,
  //   exact: true,
  //   name: ROUTES.CAMPAIGN_REPORT.name,
  //   displayName: ROUTES.CAMPAIGN_REPORT.title,
  //   component: () => ROUTES.CAMPAIGN_REPORT.title,
  //   isPrivate: true,
  //   icon: "BarChartOutlined",
  //   module: 10,
  //   category: "ReportsManagement",
  //   subCategory: "Campaign",
  //   action: "List",
  // },
  {
    path: ROUTES.LANDING_PAGE_MANAGEMENT.path,
    exact: true,
    name: ROUTES.LANDING_PAGE_MANAGEMENT.name,
    displayName: ROUTES.LANDING_PAGE_MANAGEMENT.title,
    component: LandingPageManagementProvider,
    isPrivate: true,
    icon: "BarChartOutlined",
    isDisabled: false,
    module: 8,
    category: "LandingManagement",
    subCategory: "Profiler",
    action: "List",
  },
  {
    path: `${ROUTES.SWIM_LANE_MANAGER.path}/:id`,
    exact: true,
    name: ROUTES.SWIM_LANE_MANAGER.name,
    displayName: ROUTES.SWIM_LANE_MANAGER.title,
    component: SwimLaneManagerProvider,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 8,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.LANDING_PAGE_MANAGEMENT.name,
    category: "LandingManagement",
    subCategory: "Profiler",
    action: "Add",
  },
  {
    path: ROUTES.ADD_PROFILER.path,
    exact: true,
    name: ROUTES.ADD_PROFILER.name,
    displayName: ROUTES.ADD_PROFILER.title,
    component: AddEditProfilerProvider,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 8,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.LANDING_PAGE_MANAGEMENT.name,
    category: "LandingManagement",
    subCategory: "Profiler",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_PROFILER.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_PROFILER.name,
    displayName: ROUTES.EDIT_PROFILER.title,
    component: AddEditProfilerProvider,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 8,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.LANDING_PAGE_MANAGEMENT.name,
    category: "LandingManagement",
    subCategory: "Profiler",
    action: "Edit",
  },
  {
    path: `${ROUTES.LANDING_PAGE_DESIGNER.path}/:id`,
    exact: true,
    name: ROUTES.LANDING_PAGE_DESIGNER.name,
    displayName: ROUTES.LANDING_PAGE_DESIGNER.title,
    component: LandingPageDesignerProvider,
    isPrivate: true,
    icon: "BarChartOutlined",
    module: 8,
    isHiddenInMenu: true,
    hideInSideBar: true,
    parentRouteName: ROUTES.LANDING_PAGE_MANAGEMENT.name,
    category: "LandingManagement",
    subCategory: "Designer",
    action: "Edit",
  },
  // Phase-1 Work
  {
    path: ROUTES.OUTLET_BILLING_MANAGMENT.path,
    exact: true,
    name: ROUTES.OUTLET_BILLING_MANAGMENT.name,
    displayName: ROUTES.OUTLET_BILLING_MANAGMENT.title,
    component: OutletBillingManagementProvider,
    isPrivate: true,
    icon: "UsergroupAddOutlined",
    module: 2,
    category: "PartnerManagement",
    subCategory: "OutletBillingManagement",
    action: "List",
  },
  {
    path: ROUTES.ADD_ITEM.path,
    exact: true,
    name: ROUTES.ADD_ITEM.name,
    displayName: ROUTES.ADD_ITEM.title,
    component: AddEditItemProvider,
    isPrivate: true,
    // icon: "",
    isHiddenInMenu: true,
    hideInSideBar: true,
    // module: ,
    // parentRouteName: ,
    category: "RestaurantManagement",
    subCategory: "Item",
    action: "Add",
  },
  {
    path: `${ROUTES.EDIT_ITEM.path}/:id`,
    exact: true,
    name: ROUTES.EDIT_ITEM.name,
    displayName: ROUTES.EDIT_ITEM.title,
    component: AddEditItemProvider,
    isPrivate: true,
    // icon: "",
    isHiddenInMenu: true,
    hideInSideBar: true,
    // module: ,
    // parentRouteName: ,
    category: "RestaurantManagement",
    subCategory: "Item",
    action: "Edit",
  },
];

export default routes;
