import mapValues from "lodash/mapValues";

const ACTIONS = {
  APP_RESET: null,
  USER_REQUEST: null,
  USER_SUCCESS: null,
  USER_ERROR: null,
  GET_USER_CAPABILITIES_SUCCESS: null,
  GET_USER_NOTIFICATIONS_SUCCESS: null,
  GET_ALL_USERS_SUCCESS: null,

  ADMIN_LIST_SUCCESS: null,
  SELECTED_ADMIN_SUCCESS: null,
  ADMIN_REQUEST: null,
  ADMIN_SUCCESS: null,
  ADMIN_ERROR: null,

  GET_MERCHANT_ALL_USERS_SUCCESS: null,
  GET_MERCHANT_ALL_USERS_LIST_SUCCESS: null,
  GET_MERCHANT_USERBYID_SUCCESS: null,
  MERCHANT_USER_REQUEST: null,
  MERCHANT_USER_SUCCESS: null,
  MERCHANT_USER_ERROR: null,
  SELECTED_MERCHANT_SUCCESS: null,

  GET_SESSION_ALL_USERS_SUCCESS: null,
  GET_SESSION_ALL_USERS_LIST_SUCCESS: null,
  GET_SESSION_USERBYID_SUCCESS: null,
  SESSION_USER_REQUEST: null,
  SESSION_USER_SUCCESS: null,
  SESSION_USER_ERROR: null,

  DEAL_REQUEST: null,
  DEAL_SUCCESS: null,
  DEAL_ERROR: null,
  DEAL_LIST_SUCCESS: null,
  SELECTED_DEAL_REQUEST: null,
  SELECTED_DEAL_ERROR: null,
  SELECTED_DEAL_SUCCESS: null,
  SELECTED_DEAL_LIST_SUCCESS: null,
  DEAL_FILTER_LIST_SUCCESS: null,
  POPULAR_DEALS_REQUEST: null,
  POPULAR_DEALS_ERROR: null,
  POPULAR_DEALS_LIST_SUCCESS: null,

  AREA_SEGMENT_REQUEST: null,
  AREA_SEGMENT_SUCCESS: null,
  AREA_SEGMENT_ERROR: null,
  AREA_SEGMENT_LIST_SUCCESS: null,
  SELECTED_AREA_SEGMENT_SUCCESS: null,
  AREA_STATE_SUCCESS: null,

  DEAL_CATEGORY_REQUEST: null,
  DEAL_CATEGORY_SUCCESS: null,
  DEAL_CATEGORY_ERROR: null,
  DEAL_CATEGORY_LIST_SUCCESS: null,
  SELECTED_DEAL_CATEGORY_SUCCESS: null,

  UI_REQUEST: null,
  UI_SUCCESS: null,
  UI_ERROR: null,

  CHANGE_PARTNER_REQUEST: null,
  CHANGE_PARTNER_SUCCESS: null,
  CHANGE_PARTNER_ERROR: null,

  CONSUMER_REQUEST: null,
  CONSUMER_SUCCESS: null,
  CONSUMER_ERROR: null,
  GET_CONSUMER_ALL_USERS_SUCCESS: null,
  GET_CONSUMER_BY_ID_SUCCESS: null,

  UPDATE_CONSUMER_SUCCESS: null,

  CORPORATE_CLIENT_REQUEST: null,
  CORPORATE_CLIENT_SUCCESS: null,
  CORPORATE_CLIENT_ERROR: null,
  CORPORATE_CLIENT_LIST_SUCCESS: null,
  SELECTED_CORPORATE_CLIENT_SUCCESS: null,

  BOOK_SUBSCRIPTION_REQUEST: null,
  BOOK_SUBSCRIPTION_SUCCESS: null,
  BOOK_SUBSCRIPTION_ERROR: null,
  BOOK_SUBSCRIPTION_LIST_SUCCESS: null,
  SELECTED_BOOK_SUBSCRIPTION_SUCCESS: null,

  CAMPAIGN_STATUS_REQUEST: null,
  CAMPAIGN_STATUS_SUCCESS: null,
  CAMPAIGN_STATUS_ERROR: null,
  CAMPAIGN_STATUS_LIST_SUCCESS: null,
  SELECTED_CAMPAIGN_STATUS_SUCCESS: null,

  VOUCHER_REDEMPTION_REQUEST: null,
  VOUCHER_REDEMPTION_SUCCESS: null,
  VOUCHER_REDEMPTION_ERROR: null,
  VOUCHER_REDEMPTION_LIST_SUCCESS: null,
  SELECTED_VOUCHER_REDEMPTION_SUCCESS: null,
  VOUCHER_REDEMPTION_MODAL_SHOW: null,

  BOOK_MANAGEMENT_REQUEST: null,
  BOOK_MANAGEMENT_SUCCESS: null,
  BOOK_MANAGEMENT_ERROR: null,
  BOOK_MANAGEMENT_LIST_SUCCESS: null,
  SELECTED_BOOK_MANAGEMENT_SUCCESS: null,

  PARTNER_REQUEST: null,
  PARTNER_SUCCESS: null,
  PARTNER_ERROR: null,
  PARTNER_LIST_SUCCESS: null,
  PARTNER_FILTER_LIST_SUCCESS: null,
  SELECTED_PARTNER_SUCCESS: null,

  BILLING_REQUEST: null,
  BILLING_SUCCESS: null,
  BILLING_ERROR: null,
  BILLING_LIST_SUCCESS: null,
  BILLING_FILTER_LIST_SUCCESS: null,
  SELECTED_BILLING_SUCCESS: null,

  BOOK_ORDERS_REQUEST: null,
  BOOK_ORDERS_SUCCESS: null,
  BOOK_ORDERS_ERROR: null,
  BOOK_ORDERS_LIST_SUCCESS: null,
  SELECTED_BOOK_ORDERS_SUCCESS: null,

  BRAND_REQUEST: null,
  BRAND_SUCCESS: null,
  BRAND_ERROR: null,
  BRAND_LIST_SUCCESS: null,
  BRAND_FILTER_LIST_SUCCESS: null,
  SELECTED_BRAND_SUCCESS: null,
  BOOK_BRAND_REQUEST: null,
  BOOK_BRAND_ERROR: null,
  BOOK_BRAND_LIST_SUCCESS: null,
  SELECTED_BOOK_BRAND_LIST_SUCCESS: null,
  ADD_SELECTED_BOOK_BRAND_LIST_SUCCESS: null,

  CAMPAIGN_REQUEST: null,
  CAMPAIGN_SUCCESS: null,
  CAMPAIGN_ERROR: null,
  CAMPAIGN_LIST_SUCCESS: null,
  SELECTED_CAMPAIGN_SUCCESS: null,

  PROFILER_REQUEST: null,
  PROFILER_SUCCESS: null,
  PROFILER_ERROR: null,
  PROFILER_LIST_SUCCESS: null,
  SELECTED_PROFILER_SUCCESS: null,
  SWIMLANE_SUCCESS: null,

  DESIGNER_REQUEST: null,
  DESIGNER_SUCCESS: null,
  DESIGNER_ERROR: null,

  BOOK_ORDER_PURCHASE_REPORTS_REQUEST: null,
  BOOK_ORDER_PURCHASE_REPORTS_SUCCESS: null,
  BOOK_ORDER_PURCHASE_REPORTS_ERROR: null,
  BOOK_ORDER_PURCHASE_REPORTS_LIST_SUCCESS: null,

  UPLOAD_REQUEST: null,
  UPLOAD_SUCCESS: null,
  UPLOAD_ERROR: null,

  LOCATIONS_SUCCESS: null,

  MERCHANT_DAILY_RECORD_REQUEST: null,
  MERCHANT_DAILY_RECORD_SUCCESS: null,
  MERCHANT_DAILY_RECORD_ERROR: null,
  MERCHANT_DAILY_RECORD_LIST_SUCCESS: null,

  PARTICIPANT_REQUEST: null,
  PARTICIPANT_SUCCESS: null,
  PARTICIPANT_ERROR: null,
  PARTICIPANT_LIST_SUCCESS: null,
  SELECTED_PARTICIPANT_SUCCESS: null,

  PARTICIPANT_BY_MOSQUE_AND_SESSION_REQUEST: null,
  PARTICIPANT_BY_MOSQUE_AND_SESSION_SUCCESS: null,
  PARTICIPANT_BY_MOSQUE_AND_SESSION_ERROR: null,
  PARTICIPANT_BY_MOSQUE_AND_SESSION_LIST_SUCCESS: null,
  SELECTED_PARTICIPANT_BY_MOSQUE_AND_SESSION_SUCCESS: null,

  VOLUNTEER_REQUEST: null,
  VOLUNTEER_SUCCESS: null,
  VOLUNTEER_ERROR: null,
  VOLUNTEER_LIST_SUCCESS: null,
  SELECTED_VOLUNTEER_SUCCESS: null,

  VOLUNTEER_BY_MOSQUE_AND_SESSION_REQUEST: null,
  VOLUNTEER_BY_MOSQUE_AND_SESSION_SUCCESS: null,
  VOLUNTEER_BY_MOSQUE_AND_SESSION_ERROR: null,
  VOLUNTEER_BY_MOSQUE_AND_SESSION_LIST_SUCCESS: null,
  SELECTED_VOLUNTEER_BY_MOSQUE_AND_SESSION_SUCCESS: null,

  MOSQUE_REQUEST: null,
  MOSQUE_SUCCESS: null,
  MOSQUE_ERROR: null,
  MOSQUE_LIST_SUCCESS: null,
  SELECTED_MOSQUE_SUCCESS: null,

  // SMS Utility
  SMS_UTILITY_REQUEST: null,
  SMS_UTILITY_SUCCESS: null,
  SMS_UTILITY_ERROR: null,
  SMS_UTILITY_LIST_SUCCESS: null,
  SELECTED_SMS_UTILITY_SUCCESS: null,

  // Musalli Attendance BULK
  MUSALLI_ATTENDANCE_BULK_REQUEST: null,
  MUSALLI_ATTENDANCE_BULK_SUCCESS: null,
  MUSALLI_ATTENDANCE_BULK_ERROR: null,
  MUSALLI_ATTENDANCE_BULK_LIST_SUCCESS: null,
  SELECTED_MUSALLI_ATTENDANCE_BULK_SUCCESS: null,

  // Musalli Attendance Detail Report

  MUSALLI_ATTENDANCE_DETAIL_REPORT_REQUEST: null,
  MUSALLI_ATTENDANCE_DETAIL_REPORT_SUCCESS: null,
  MUSALLI_ATTENDANCE_DETAIL_REPORT_ERROR: null,
  MUSALLI_ATTENDANCE_DETAIL_REPORT_LIST_SUCCESS: null,
  SELECTED_MUSALLI_ATTENDANCE_DETAIL_REPORT_SUCCESS: null,

  ACTIVE_MOSQUE_BY_SESSION_REQUEST: null,
  ACTIVE_MOSQUE_BY_SESSION_SECCESS: null,
  ACTIVE_MOSQUE_BY_SESSION_ERROR: null,
  ACTIVE_MOSQUE_BY_SESSION_LIST_SUCCESS: null,
  SELECTED_ACTIVE_MOSQUE_BY_SESSION_SUCCESS: null,

  // Get All Active Session

  ACTIVE_SESSION_REQUEST: null,
  ACTIVE_SESSION_SUCCESS: null,
  ACTIVE_SESSION_ERROR: null,
  ACTIVE_SESSION_LIST_SUCCESS: null,
  SELECTED_ACTIVE_SESSION_SUCCESS: null,
};

export default mapValues(ACTIONS, (v, k) => k);
