export const bookOrderPurchaseReports = {
  content: [
    {
      id: "1",
      customerName: "abc",
      customerContact: "156464665",
      customerEmail: "abc@gmail.com",
      bookName: "abc book",
      bookCode: "0014578B",
      isActive: "true",
      isUsed: "true",
      blocked: "true",
      verified: "false",
      city: "Lahor",
      activationDate: "1588060094078",
      activationTime: "1588060094078",
      deviceName: "android",
    },
    {
      id: "2",
      customerName: "cde",
      customerContact: "156464665",
      customerEmail: "cde@gmail.com",
      bookName: "cde book",
      bookCode: "0014578B",
      isActive: "true",
      isUsed: "true",
      blocked: "true",
      verified: "false",
      city: "Lahor",
      activationDate: "1588060094078",
      activationTime: "1588060094078",
      deviceName: "android",
    },
    {
      id: "3",
      customerName: "efg",
      customerContact: "156464665",
      customerEmail: "efg@gmail.com",
      bookName: "efg book",
      bookCode: "0014578B",
      isActive: "true",
      isUsed: "true",
      blocked: "true",
      verified: "false",
      city: "Lahor",
      activationDate: "1588060094078",
      activationTime: "1588060094078",
      deviceName: "android",
    },
    {
      id: "4",
      customerName: "hig",
      customerContact: "156464665",
      customerEmail: "hij@gmail.com",
      bookName: "hij book",
      bookCode: "0014578B",
      isActive: "true",
      isUsed: "true",
      blocked: "true",
      verified: "false",
      city: "Lahor",
      activationDate: "1588060094078",
      activationTime: "1588060094078",
      deviceName: "android",
    },
    {
      id: "5",
      customerName: "klm",
      customerContact: "156464665",
      customerEmail: "klm@gmail.com",
      bookName: "klm book",
      bookCode: "0014578B",
      isActive: "true",
      isUsed: "true",
      blocked: "true",
      verified: "false",
      city: "Lahor",
      activationDate: "1588060094078",
      activationTime: "1588060094078",
      deviceName: "android",
    },
    {
      id: "6",
      customerName: "mno",
      customerContact: "156464665",
      customerEmail: "mno@gmail.com",
      bookName: "mno book",
      bookCode: "0014578B",
      isActive: "true",
      isUsed: "true",
      blocked: "true",
      verified: "false",
      city: "Lahor",
      activationDate: "1588060094078",
      activationTime: "1588060094078",
      deviceName: "android",
    },
  ],
  pageable: {
    sort: {
      sorted: false,
      unsorted: true,
    },
    offset: 0,
    pageSize: 10,
    pageNumber: 0,
    unpaged: false,
    paged: true,
  },
  last: true,
  totalElements: 13,
  totalPages: 2,
  size: 10,
  number: 0,
  sort: {
    sorted: false,
    unsorted: true,
  },
  numberOfElements: 10,
  first: true,
};
