export const bookObj = {
  id: 3,
  code: "bdbb5c39-9d7c-4292-9cf0-17949035eedd",
  recordStatus: "LIVE",
  createdBy: "system",
  createdDate: 1589203058713,
  lastModifiedBy: "malik",
  lastModifiedDate: 1589204936963,
  title: "Test Book 3",
  price: 7000.0,
  eventName: "Test Book 4",
  startDate: 1588339054396,
  endDate: 1590844655170,
  cityId: "multan",
  bookDeals: null,
  bookDealsMap: { "2542e267-18e7-42f5-85c5-3c3ea40cd481": "2542e267-18e7-42f5-85c5-3c3ea40cd481" },
  bookDetail: {
    id: 3,
    code: "9dfdce05-d429-4383-bb47-bf1beb287ae1",
    bookBrands: null,
    popularDeals: null,
    popularBrands: null,
    bookBrandsMap: { "1": "1", "3": "3", "333": "333" },
    popularDealsMap: { "122": "122", "13": "13" },
    popularBrandsMap: { "1": "1", "3": "3", "333": "333" },
  },
  customerCode: null,
  maxPurchaseCount: null,
  discountedPrice: 66.0,
  visibility: "PRIVATE",
  organization: null,
  punchline: "Test Book 3",
  description: "Test Book 3",
  bannerImageUrl: null,
  imageUrls: null,
  buyNowUrl: null,
  saving: 0.0,
  status: "PUBLISHED",
  detail: null,
  shareable: false,
  enabled: true,
};

export const bookManagement = {
  content: [
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      bookId: 1,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",

      active: false,
      status: "PUBLISHED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      bookId: 2,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",

      active: false,
      status: "PUBLISHED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      bookId: 3,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",

      active: false,
      status: "PUBLISHED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      bookId: 4,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",

      active: false,
      status: "PUBLISHED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      bookId: 5,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",

      active: false,
      status: "PUBLISHED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      bookId: 6,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",

      active: false,
      status: "PUBLISHED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      bookId: 7,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",

      active: false,
      status: "PUBLISHED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      bookId: 8,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",

      active: false,
      status: "PUBLISHED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      bookId: 9,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",

      active: false,
      status: "PUBLISHED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      bookId: 10,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",

      active: false,
      status: "PUBLISHED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      bookId: 11,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",

      active: false,
      status: "PUBLISHED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      bookId: 12,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",

      active: false,
      status: "PUBLISHED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      bookId: 13,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",

      active: false,
      status: "PUBLISHED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
  ],
  pageable: {
    sort: {
      sorted: false,
      unsorted: true,
    },
    offset: 0,
    pageSize: 10,
    pageNumber: 0,
    unpaged: false,
    paged: true,
  },
  last: true,
  totalElements: 13,
  totalPages: 2,
  size: 10,
  number: 0,
  sort: {
    sorted: false,
    unsorted: true,
  },
  numberOfElements: 10,
  first: true,
};
export const bookLocationList = [
  { name: "Karachi", code: "karachi" },
  { name: "Multan", code: "multan" },
  { name: "Lahore", code: "lahore" },
  { name: "Islamabad", code: "lahore" },
];
export const bookTypeList = ["BOGO", "Gift", "Discount", "Discount on other item", "Other"];
export const bookOrders = {
  content: [
    {
      bookOrderId: 1,
      requestTimeStamp: "12568823131",
      purchaseRequestId: 1,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      price: 10000,
      consumerId: 1,
      bookId: 1,
      consumerName: "Food Panda",
      paymentTransactionId: "36468326786",
      failureRejectionReason: "abc",
      active: false,
      status: "AUTHORIZED",
      paymentStatus: "PAID",
    },
    {
      bookOrderId: 2,
      requestTimeStamp: "1899883131",
      purchaseRequestId: 2,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      price: 9000,
      consumerId: 2,
      bookId: 2,
      consumerName: "Lavaish",
      paymentTransactionId: "36468326786",
      failureRejectionReason: "abc",
      active: true,
      status: "REJECTED",
      paymentStatus: "NON PAID",
    },
    {
      bookOrderId: 3,
      requestTimeStamp: "909123131",
      purchaseRequestId: 3,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      price: 10000,
      consumerId: 3,
      bookId: 3,
      consumerName: "Food Panda",
      paymentTransactionId: "36468326786",
      failureRejectionReason: "abc",
      active: false,
      status: "AUTHORIZED",
      paymentStatus: "PAID",
    },
    {
      bookOrderId: 4,
      requestTimeStamp: "123123131",
      purchaseRequestId: 4,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "Clifton",
      price: 20000,
      consumerId: 4,
      bookId: 4,
      consumerName: "Food Panda",
      paymentTransactionId: "36468326786",
      failureRejectionReason: "abc",
      active: false,
      status: "REJECTED",
      paymentStatus: "PAID",
    },
    {
      bookOrderId: 5,
      requestTimeStamp: "123123131",
      purchaseRequestId: 5,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      price: 10000,
      consumerId: 5,
      bookId: 5,
      consumerName: "Food Panda",
      paymentTransactionId: "36468326786",
      failureRejectionReason: "abc",
      active: true,
      status: "AUTHORIZED",
      paymentStatus: "NON PAID",
    },
    {
      bookOrderId: 6,
      requestTimeStamp: "123123131",
      purchaseRequestId: 6,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      price: 10000,
      consumerId: 6,
      bookId: 6,
      consumerName: "Food Panda",
      paymentTransactionId: "36468326786",
      failureRejectionReason: "abc",
      active: false,
      status: "AUTHORIZED",
      paymentStatus: "PAID",
    },
    {
      bookOrderId: 7,
      requestTimeStamp: "123123131",
      purchaseRequestId: 7,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      price: 10000,
      consumerId: 7,
      bookId: 7,
      consumerName: "Food Panda",
      paymentTransactionId: "36468326786",
      failureRejectionReason: "abc",
      active: false,
      status: "PUBLISHED",
      paymentStatus: "PAID",
    },
    {
      bookOrderId: 8,
      requestTimeStamp: "123123131",
      purchaseRequestId: 8,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      price: 10000,
      consumerId: 8,
      bookId: 8,
      consumerName: "Food Panda",
      paymentTransactionId: "36468326786",
      failureRejectionReason: "abc",
      active: false,
      status: "AUTHORIZED",
      paymentStatus: "PAID",
    },
    {
      bookOrderId: 9,
      requestTimeStamp: "123123131",
      purchaseRequestId: 9,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      price: 10000,
      consumerId: 9,
      bookId: 9,
      consumerName: "Food Panda",
      paymentTransactionId: "36468326786",
      failureRejectionReason: "abc",
      active: false,
      status: "REJECTED",
      paymentStatus: "PAID",
    },
    {
      bookOrderId: 10,
      requestTimeStamp: "123123131",
      purchaseRequestId: 10,
      bookName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      price: 10000,
      consumerId: 10,
      bookId: 10,
      consumerName: "Food Panda",
      paymentTransactionId: "36468326786",
      failureRejectionReason: "abc",
      active: false,
      status: "AUTHORIZED",
      paymentStatus: "PAID",
    },
  ],
  pageable: {
    sort: {
      sorted: false,
      unsorted: true,
    },
    offset: 0,
    pageSize: 10,
    pageNumber: 0,
    unpaged: false,
    paged: true,
  },
  last: true,
  totalElements: 13,
  totalPages: 2,
  size: 10,
  number: 0,
  sort: {
    sorted: false,
    unsorted: true,
  },
  numberOfElements: 10,
  first: true,
};
