export const bookSubscription = {
  content: [
    {
      bookSubscriptionId: 1,
      corporateCustomerId: 1,
      customerName: "Nisum Pvt. Ltd.",
      bookLocationId: 1,
      bookId: 1,
      bookName: "Nisum Employees",
      bookPrice: "3500",
      startDate: "03-26-2020",
      endDate: "03-26-2021",
      requestTime: "02-28-2020 15:30:00",
      noOfEmployees: 5,
      totalSubscriptionCost: 4500,
      isEnabled: true,
      active: true,
    },
    {
      bookSubscriptionId: 2,
      corporateCustomerId: 1,
      customerName: "Nisum Pvt. Ltd.",
      bookLocationId: 1,
      bookId: 1,
      bookName: "Nisum Employees",
      bookPrice: "3500",
      startDate: "03-26-2020",
      endDate: "03-26-2021",
      requestTime: "02-28-2020 15:30:00",
      noOfEmployees: 5,
      totalSubscriptionCost: 4500,
      isEnabled: true,
      active: true,
    },
    {
      bookSubscriptionId: 3,
      corporateCustomerId: 1,
      customerName: "Nisum Pvt. Ltd.",
      bookLocationId: 1,
      bookId: 1,
      bookName: "Nisum Employees",
      bookPrice: "3500",
      startDate: "03-26-2020",
      endDate: "03-26-2021",
      requestTime: "02-28-2020 15:30:00",
      noOfEmployees: 5,
      totalSubscriptionCost: 4500,
      isEnabled: true,
      active: true,
    },
    {
      bookSubscriptionId: 4,
      corporateCustomerId: 1,
      customerName: "Nisum Pvt. Ltd.",
      bookLocationId: 1,
      bookId: 1,
      bookName: "Nisum Employees",
      bookPrice: "3500",
      startDate: "03-26-2020",
      endDate: "03-26-2021",
      requestTime: "02-28-2020 15:30:00",
      noOfEmployees: 5,
      totalSubscriptionCost: 4500,
      isEnabled: true,
      active: true,
    },
    {
      bookSubscriptionId: 5,
      corporateCustomerId: 1,
      customerName: "Nisum Pvt. Ltd.",
      bookLocationId: 1,
      bookId: 1,
      bookName: "Nisum Employees",
      bookPrice: "3500",
      startDate: "03-26-2020",
      endDate: "03-26-2021",
      requestTime: "02-28-2020 15:30:00",
      noOfEmployees: 5,
      totalSubscriptionCost: 4500,
      isEnabled: true,
      active: true,
    },
  ],
  pageable: {
    sort: {
      sorted: false,
      unsorted: true,
    },
    offset: 0,
    pageSize: 10,
    pageNumber: 0,
    unpaged: false,
    paged: true,
  },
  last: true,
  totalElements: 5,
  totalPages: 1,
  size: 10,
  number: 0,
  sort: {
    sorted: false,
    unsorted: true,
  },
  numberOfElements: 5,
  first: true,
};
