export const campaign = {
  content: [
    {
      campaignId: 1,
      campaignName: "Biryani",
      locationName: "DHA Phase 2 Karachi",
      eventName: "event",
      enabled: false,
      status: "Planned",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      vouchersCount: 10,
      description: "",
      location: {},
      areaSegment: "DHA",
      price: 50,
      isTransferable: false,
      categoriesCount: 6,
      brandsCount: 25,
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
    },
    {
      campaignId: 2,
      campaignName: "Biryani",
      locationName: "DHA Phase 2 Karachi",
      eventName: "event",
      enabled: false,
      status: "Planned",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      vouchersCount: 10,
      description: "",
      location: {},
      areaSegment: "DHA",
      price: 50,
      isTransferable: false,
      categoriesCount: 6,
      brandsCount: 25,
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
    },
    {
      campaignId: 3,
      campaignName: "Biryani",
      locationName: "DHA Phase 2 Karachi",
      eventName: "event",
      enabled: false,
      status: "Planned",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      vouchersCount: 10,
      description: "",
      location: {},
      areaSegment: "DHA",
      price: 50,
      isTransferable: false,
      categoriesCount: 6,
      brandsCount: 25,
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
    },
    {
      campaignId: 4,
      campaignName: "Biryani",
      locationName: "DHA Phase 2 Karachi",
      eventName: "event",
      enabled: false,
      status: "Planned",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      vouchersCount: 10,
      description: "",
      location: {},
      areaSegment: "DHA",
      price: 50,
      isTransferable: false,
      categoriesCount: 6,
      brandsCount: 25,
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
    },
    {
      campaignId: 5,
      campaignName: "Biryani",
      locationName: "DHA Phase 2 Karachi",
      eventName: "event",
      enabled: false,
      status: "Planned",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      vouchersCount: 10,
      description: "",
      location: {},
      areaSegment: "DHA",
      price: 50,
      isTransferable: false,
      categoriesCount: 6,
      brandsCount: 25,
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
    },
    {
      campaignId: 6,
      campaignName: "Biryani",
      locationName: "DHA Phase 2 Karachi",
      eventName: "event",
      enabled: false,
      status: "Planned",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      vouchersCount: 10,
      description: "",
      location: {},
      areaSegment: "DHA",
      price: 50,
      isTransferable: false,
      categoriesCount: 6,
      brandsCount: 25,
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
    },
    {
      campaignId: 7,
      campaignName: "Biryani",
      locationName: "DHA Phase 2 Karachi",
      eventName: "event",
      enabled: false,
      status: "Planned",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      vouchersCount: 10,
      description: "",
      location: {},
      areaSegment: "DHA",
      price: 50,
      isTransferable: false,
      categoriesCount: 6,
      brandsCount: 25,
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
    },
    {
      campaignId: 8,
      campaignName: "Biryani",
      locationName: "DHA Phase 2 Karachi",
      eventName: "event",
      enabled: false,
      status: "Planned",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      vouchersCount: 10,
      description: "",
      location: {},
      areaSegment: "DHA",
      price: 50,
      isTransferable: false,
      categoriesCount: 6,
      brandsCount: 25,
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
    },
    {
      campaignId: 9,
      campaignName: "Biryani",
      locationName: "DHA Phase 2 Karachi",
      eventName: "event",
      enabled: false,
      status: "Planned",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      vouchersCount: 10,
      description: "",
      location: {},
      areaSegment: "DHA",
      price: 50,
      isTransferable: false,
      categoriesCount: 6,
      brandsCount: 25,
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
    },
    {
      campaignId: 10,
      campaignName: "Biryani",
      locationName: "DHA Phase 2 Karachi",
      eventName: "event",
      enabled: false,
      status: "Planned",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      vouchersCount: 10,
      description: "",
      location: {},
      areaSegment: "DHA",
      price: 50,
      isTransferable: false,
      categoriesCount: 6,
      brandsCount: 25,
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
    },
    {
      campaignId: 11,
      campaignName: "Biryani",
      locationName: "DHA Phase 2 Karachi",
      eventName: "event",
      enabled: false,
      status: "Planned",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      vouchersCount: 10,
      description: "",
      location: {},
      areaSegment: "DHA",
      price: 50,
      isTransferable: false,
      categoriesCount: 6,
      brandsCount: 25,
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
    },
    {
      campaignId: 12,
      campaignName: "Biryani",
      locationName: "DHA Phase 2 Karachi",
      eventName: "event",
      enabled: false,
      status: "Planned",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      vouchersCount: 10,
      description: "",
      location: {},
      areaSegment: "DHA",
      price: 50,
      isTransferable: false,
      categoriesCount: 6,
      brandsCount: 25,
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
    },
    {
      campaignId: 13,
      campaignName: "Biryani",
      locationName: "DHA Phase 2 Karachi",
      eventName: "event",
      enabled: false,
      status: "Planned",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      vouchersCount: 10,
      description: "",
      location: {},
      areaSegment: "DHA",
      price: 50,
      isTransferable: false,
      categoriesCount: 6,
      brandsCount: 25,
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
    },
  ],
  pageable: {
    sort: {
      sorted: false,
      unsorted: true,
    },
    offset: 0,
    pageSize: 10,
    pageNumber: 0,
    unpaged: false,
    paged: true,
  },
  last: true,
  totalElements: 13,
  totalPages: 2,
  size: 10,
  number: 0,
  sort: {
    sorted: false,
    unsorted: true,
  },
  numberOfElements: 10,
  first: true,
};
