export const campaignStatusConsole = {
  content: [
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      campaignId: 1,
      campaignName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",
      startTimeStamp: "2020-04-07",

      active: false,
      status: "PLANNED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      numberOfvouchers: 20,
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      campaignId: 2,
      campaignName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",
      startTimeStamp: "2020-04-06",

      active: false,
      status: "Completed",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      numberOfvouchers: 20,
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      campaignId: 3,
      campaignName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",
      startTimeStamp: "2020-04-07",

      active: false,
      status: "Completed",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      numberOfvouchers: 20,
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      campaignId: 4,
      campaignName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",
      startTimeStamp: "2020-04-07",

      active: false,
      status: "PLANNED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Eat",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      numberOfvouchers: 20,
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      campaignId: 5,
      campaignName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",
      startTimeStamp: "2020-04-07",

      active: false,
      status: "PLANNED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Eat",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      numberOfvouchers: 20,
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      campaignId: 6,
      campaignName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",
      startTimeStamp: "2020-04-07",

      active: false,
      status: "PLANNED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Eat",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      numberOfvouchers: 20,
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      campaignId: 7,
      campaignName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",
      startTimeStamp: "2020-04-07",

      active: false,
      status: "PLANNED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Eat",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      numberOfvouchers: 20,
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      campaignId: 8,
      campaignName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",
      startTimeStamp: "2020-04-07",

      active: false,
      status: "PLANNED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Eat",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      numberOfvouchers: 20,
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      campaignId: 9,
      campaignName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",
      startTimeStamp: "2020-04-07",

      active: false,
      status: "PLANNED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Eat",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      numberOfvouchers: 20,
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      campaignId: 10,
      campaignName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",
      startTimeStamp: "2020-04-07",

      active: false,
      status: "InProgress",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Eat",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      numberOfvouchers: 20,
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      campaignId: 11,
      campaignName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",
      startTimeStamp: "2020-04-07",

      active: false,
      status: "InProgress",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      numberOfvouchers: 20,
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      campaignId: 12,
      campaignName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "DHA",
      expiryTimeStamp: "123456789",
      startTimeStamp: "2020-04-07",

      active: false,
      status: "PLANNED",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      numberOfvouchers: 20,
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
    {
      createdBy: "system",
      createdDate: "2020-01-01",
      lastModifiedBy: "system",
      lastModifiedDate: "2020-01-01",
      campaignId: 13,
      campaignName: "Nisum Pvt. Ltd.",
      description: "Bogo CArd Bogo Card Bogo Card",
      locationName: "Gulshan",
      expiryTimeStamp: "123456789",
      startTimeStamp: "2020-04-07",

      active: false,
      status: "InProgress",
      price: 3000,
      corporateCustomer: "Deals That bring savings",
      eventName: "Karachi Bachaoo",
      maximumdisburselimit: 10000,
      title: "Bogo Book",
      numberOfvouchers: 20,
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      punchline: "Deals That bring savings, preventing you from stress",
    },
  ],
  pageable: {
    sort: {
      sorted: false,
      unsorted: true,
    },
    offset: 0,
    pageSize: 10,
    pageNumber: 0,
    unpaged: false,
    paged: true,
  },
  last: true,
  totalElements: 13,
  totalPages: 2,
  size: 10,
  number: 0,
  sort: {
    sorted: false,
    unsorted: true,
  },
  numberOfElements: 10,
  first: true,
  locationFilter: [
    { text: "DHA", value: "DHA" },
    { text: "Gulshan", value: "Gulshan" },
  ],
  eventFilter: [
    { text: "Karachi Bachaoo", value: "Karachi Bachaoo" },
    { text: "Karachi Eat", value: "Karachi Eat" },
  ],
  statusFilter: [
    { text: "Drafted", value: "Drafted" },
    { text: "Planned", value: "PLANNED" },
    { text: "Scheduled", value: "Scheduled" },
    { text: "InProgress", value: "InProgress" },
    { text: "Disabled", value: "Disabled" },
    { text: "Completed", value: "Completed" },
    { text: "Retired", value: "Retired" },
  ],
};

export const bookLocationList = ["Karachi", "Multan", "Lahore", "Islamabad"];
export const bookTypeList = ["BOGO", "Gift", "Discount", "Discount on other item", "Other"];
