export const categoryList = {
  content: [
    {
      enabled: true,
      code: 1,
      createdBy: "string",
      createdDate: 0,
      description: "string",
      imageUrls: "string",
      lastModifiedBy: "string",
      lastModifiedDate: 0,
      logoUrl: "string",
      name: "Cat 1",
      userId: 0,
      userName: "string",
    },
    {
      enabled: true,
      code: 2,
      createdBy: "string",
      createdDate: 0,
      description: "string",
      imageUrls: "string",
      lastModifiedBy: "string",
      lastModifiedDate: 0,
      logoUrl: "string",
      name: "Cat 2",
      userId: 0,
      userName: "string",
    },
    {
      enabled: true,
      code: 3,
      createdBy: "string",
      createdDate: 0,
      description: "string",
      imageUrls: "string",
      lastModifiedBy: "string",
      lastModifiedDate: 0,
      logoUrl: "string",
      name: "Cat 3",
      userId: 0,
      userName: "string",
    },
    {
      enabled: true,
      code: 4,
      createdBy: "string",
      createdDate: 0,
      description: "string",
      imageUrls: "string",
      lastModifiedBy: "string",
      lastModifiedDate: 0,
      logoUrl: "string",
      name: "Cat 4",
      userId: 0,
      userName: "string",
    },
    {
      enabled: true,
      code: 5,
      createdBy: "string",
      createdDate: 0,
      description: "string",
      imageUrls: "string",
      lastModifiedBy: "string",
      lastModifiedDate: 0,
      logoUrl: "string",
      name: "Cat 5",
      userId: 0,
      userName: "string",
    },
    {
      enabled: true,
      code: 6,
      createdBy: "string",
      createdDate: 0,
      description: "string",
      imageUrls: "string",
      lastModifiedBy: "string",
      lastModifiedDate: 0,
      logoUrl: "string",
      name: "Cat 6",
      userId: 0,
      userName: "string",
    },
    {
      enabled: true,
      code: 7,
      createdBy: "string",
      createdDate: 0,
      description: "string",
      imageUrls: "string",
      lastModifiedBy: "string",
      lastModifiedDate: 0,
      logoUrl: "string",
      name: "Cat 7",
      userId: 0,
      userName: "string",
    },
    {
      enabled: true,
      code: 8,
      createdBy: "string",
      createdDate: 0,
      description: "string",
      imageUrls: "string",
      lastModifiedBy: "string",
      lastModifiedDate: 0,
      logoUrl: "string",
      name: "Cat 8",
      userId: 0,
      userName: "string",
    },
    {
      enabled: true,
      code: 9,
      createdBy: "string",
      createdDate: 0,
      description: "string",
      imageUrls: "string",
      lastModifiedBy: "string",
      lastModifiedDate: 0,
      logoUrl: "string",
      name: "Cat 9",
      userId: 0,
      userName: "string",
    },
    {
      enabled: true,
      code: 10,
      createdBy: "string",
      createdDate: 0,
      description: "string",
      imageUrls: "string",
      lastModifiedBy: "string",
      lastModifiedDate: 0,
      logoUrl: "string",
      name: "Cat 10",
      userId: 0,
      userName: "string",
    },
    {
      enabled: true,
      code: 11,
      createdBy: "string",
      createdDate: 0,
      description: "string",
      imageUrls: "string",
      lastModifiedBy: "string",
      lastModifiedDate: 0,
      logoUrl: "string",
      name: "Cat 11",
      userId: 0,
      userName: "string",
    },
  ],
  pageable: {
    sort: {
      sorted: false,
      unsorted: true,
    },
    offset: 0,
    pageSize: 10,
    pageNumber: 0,
    unpaged: false,
    paged: true,
  },
  last: true,
  totalElements: 14,
  totalPages: 2,
  size: 10,
  number: 0,
  sort: {
    sorted: false,
    unsorted: true,
  },
  numberOfElements: 10,
  first: true,
};
