export const corporateCustomer = {
  content: [
    {
      clientId: 1,
      clientName: "Nisum Pvt. Ltd.",
      locationName: "DHA",
      email: "client@email.com",
      landLineNumber: "123456789",
      cellNumber: "123456789",
      otherEmail: "other@email.com",
      pocName: "Danish",
      pocDesignation: "Employee",
      pocContactNumber: "123456789",
      pocEmailAddr: "danish@nisum.com",
      active: false,
    },
    {
      clientId: 2,
      clientName: "Nisum Pvt. Ltd.",
      locationName: "DHA",
      email: "client@email.com",
      landLineNumber: "123456789",
      cellNumber: "123456789",
      otherEmail: "other@email.com",
      pocName: "Danish",
      pocDesignation: "Employee",
      pocContactNumber: "123456789",
      pocEmailAddr: "danish@nisum.com",
      active: false,
    },
    {
      clientId: 3,
      clientName: "Nisum Pvt. Ltd.",
      locationName: "DHA",
      email: "client@email.com",
      landLineNumber: "123456789",
      cellNumber: "123456789",
      otherEmail: "other@email.com",
      pocName: "Danish",
      pocDesignation: "Employee",
      pocContactNumber: "123456789",
      pocEmailAddr: "danish@nisum.com",
      active: false,
    },
    {
      clientId: 4,
      clientName: "Nisum Pvt. Ltd.",
      locationName: "DHA",
      email: "client@email.com",
      landLineNumber: "123456789",
      cellNumber: "123456789",
      otherEmail: "other@email.com",
      pocName: "Danish",
      pocDesignation: "Employee",
      pocContactNumber: "123456789",
      pocEmailAddr: "danish@nisum.com",
      active: false,
    },
    {
      clientId: 5,
      clientName: "Nisum Pvt. Ltd.",
      locationName: "DHA",
      email: "client@email.com",
      landLineNumber: "123456789",
      cellNumber: "123456789",
      otherEmail: "other@email.com",
      pocName: "Danish",
      pocDesignation: "Employee",
      pocContactNumber: "123456789",
      pocEmailAddr: "danish@nisum.com",
      active: false,
    },
    {
      clientId: 6,
      clientName: "Nisum Pvt. Ltd.",
      locationName: "DHA",
      email: "client@email.com",
      landLineNumber: "123456789",
      cellNumber: "123456789",
      otherEmail: "other@email.com",
      pocName: "Danish",
      pocDesignation: "Employee",
      pocContactNumber: "123456789",
      pocEmailAddr: "danish@nisum.com",
      active: false,
    },
    {
      clientId: 7,
      clientName: "Nisum Pvt. Ltd.",
      locationName: "DHA",
      email: "client@email.com",
      landLineNumber: "123456789",
      cellNumber: "123456789",
      otherEmail: "other@email.com",
      pocName: "Danish",
      pocDesignation: "Employee",
      pocContactNumber: "123456789",
      pocEmailAddr: "danish@nisum.com",
      active: false,
    },
    {
      clientId: 8,
      clientName: "Nisum Pvt. Ltd.",
      locationName: "DHA",
      email: "client@email.com",
      landLineNumber: "123456789",
      cellNumber: "123456789",
      otherEmail: "other@email.com",
      pocName: "Danish",
      pocDesignation: "Employee",
      pocContactNumber: "123456789",
      pocEmailAddr: "danish@nisum.com",
      active: false,
    },
    {
      clientId: 9,
      clientName: "Nisum Pvt. Ltd.",
      locationName: "DHA",
      email: "client@email.com",
      landLineNumber: "123456789",
      cellNumber: "123456789",
      otherEmail: "other@email.com",
      pocName: "Danish",
      pocDesignation: "Employee",
      pocContactNumber: "123456789",
      pocEmailAddr: "danish@nisum.com",
      active: false,
    },
    {
      clientId: 10,
      clientName: "Nisum Pvt. Ltd.",
      locationName: "DHA",
      email: "client@email.com",
      landLineNumber: "123456789",
      cellNumber: "123456789",
      otherEmail: "other@email.com",
      pocName: "Danish",
      pocDesignation: "Employee",
      pocContactNumber: "123456789",
      pocEmailAddr: "danish@nisum.com",
      active: false,
    },
    {
      clientId: 11,
      clientName: "Nisum Pvt. Ltd.",
      locationName: "DHA",
      email: "client@email.com",
      landLineNumber: "123456789",
      cellNumber: "123456789",
      otherEmail: "other@email.com",
      pocName: "Danish",
      pocDesignation: "Employee",
      pocContactNumber: "123456789",
      pocEmailAddr: "danish@nisum.com",
      active: false,
    },
    {
      clientId: 12,
      clientName: "Nisum Pvt. Ltd.",
      locationName: "DHA",
      email: "client@email.com",
      landLineNumber: "123456789",
      cellNumber: "123456789",
      otherEmail: "other@email.com",
      pocName: "Danish",
      pocDesignation: "Employee",
      pocContactNumber: "123456789",
      pocEmailAddr: "danish@nisum.com",
      active: false,
    },
    {
      clientId: 13,
      clientName: "Nisum Pvt. Ltd.",
      locationName: "DHA",
      email: "client@email.com",
      landLineNumber: "123456789",
      cellNumber: "123456789",
      otherEmail: "other@email.com",
      pocName: "Danish",
      pocDesignation: "Employee",
      pocContactNumber: "123456789",
      pocEmailAddr: "danish@nisum.com",
      active: false,
    },
  ],
  pageable: {
    sort: {
      sorted: false,
      unsorted: true,
    },
    offset: 0,
    pageSize: 10,
    pageNumber: 0,
    unpaged: false,
    paged: true,
  },
  last: true,
  totalElements: 13,
  totalPages: 2,
  size: 10,
  number: 0,
  sort: {
    sorted: false,
    unsorted: true,
  },
  numberOfElements: 10,
  first: true,
};
