export const profiler = {
  content: [
    {
      profilerId: 1,
      name: "Nisum Pvt.",
      description: "Profiler",
      city: "karachi",
      enable: "Disabled",
      createdAt: "2020-04-07T10:56:35.748+0000",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      segmentName: "Gul Ahmed",
      type: "Permanent",
      status: "ACTIVE",
    },
    {
      profilerId: 2,
      name: "Nisum Pvt. Ltd.",
      description: "Profiler",
      city: "karachi",
      enable: "Enabled",
      createdAt: "2020-04-07T10:56:35.748+0000",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      segmentName: "Gul Ahmed",
      type: "Permanent",
      status: "ACTIVE",
    },
    {
      profilerId: 3,
      name: "Nisum Pvt. Ltd.",
      description: "Profiler",
      city: "karachi",
      enable: "Enabled",
      createdAt: "2020-04-07T10:56:35.748+0000",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      segmentName: "Gul Ahmed",
      type: "Permanent",
      status: "ACTIVE",
    },
    {
      profilerId: 4,
      name: "Nisum Pvt. Ltd.",
      description: "Profiler",
      city: "karachi",
      enable: "Enabled",
      createdAt: "2020-04-07T10:56:35.748+0000",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      segmentName: "Gul Ahmed",
      type: "Permanent",
      status: "ACTIVE",
    },
    {
      profilerId: 5,
      name: "Nisum Pvt. Ltd.",
      description: "Profiler",
      city: "karachi",
      enable: "Enabled",
      createdAt: "2020-04-07T10:56:35.748+0000",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      segmentName: "Gul Ahmed",
      type: "Permanent",
      status: "ACTIVE",
    },
    {
      profilerId: 6,
      name: "Nisum Pvt. Ltd.",
      description: "Profiler",
      city: "karachi",
      enable: "Enabled",
      createdAt: "2020-04-07T10:56:35.748+0000",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      segmentName: "Gul Ahmed",
      type: "Permanent",
      status: "ACTIVE",
    },
    {
      profilerId: 7,
      name: "Nisum Pvt. Ltd.",
      description: "Profiler",
      city: "karachi",
      enable: "Enabled",
      createdAt: "2020-04-07T10:56:35.748+0000",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      segmentName: "Gul Ahmed",
      type: "Permanent",
      status: "ACTIVE",
    },
    {
      profilerId: 8,
      name: "Nisum Pvt. Ltd.",
      description: "Profiler",
      city: "karachi",
      enable: "Enabled",
      createdAt: "2020-04-07T10:56:35.748+0000",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      segmentName: "Gul Ahmed",
      type: "Temporary",
      status: "DORMANT",
    },
    {
      profilerId: 9,
      name: "Nisum Pvt. Ltd.",
      description: "Profiler",
      city: "karachi",
      enable: "Enabled",
      createdAt: "2020-04-07T10:56:35.748+0000",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      segmentName: "Gul Ahmed",
      type: "Temporary",
      status: "DORMANT",
    },
    {
      profilerId: 10,
      name: "Nisum Pvt. Ltd.",
      description: "Profiler",
      city: "karachi",
      enable: "Enabled",
      createdAt: "2020-04-07T10:56:35.748+0000",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      segmentName: "Gul Ahmed",
      type: "Temporary",
      status: "DORMANT",
    },
    {
      profilerId: 11,
      name: "Nisum Pvt. Ltd.",
      description: "Profiler",
      city: "karachi",
      enable: "Enabled",
      createdAt: "2020-04-07T10:56:35.748+0000",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      segmentName: "Gul Ahmed",
      type: "Temporary",
      status: "DORMANT",
    },
    {
      profilerId: 12,
      name: "Nisum Pvt. Ltd.",
      description: "Profiler",
      city: "karachi",
      enable: "Enabled",
      createdAt: "2020-04-07T10:56:35.748+0000",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      segmentName: "Gul Ahmed",
      type: "Temporary",
      status: "DORMANT",
    },
    {
      profilerId: 13,
      name: "Nisum Pvt. Ltd.",
      description: "Profiler",
      city: "karachi",
      enable: "Enabled",
      createdAt: "2020-04-07T10:56:35.748+0000",
      startDate: "2020-01-01",
      endDate: "2020-01-01",
      segmentName: "Gul Ahmed",
      type: "Temporary",
      status: "DORMANT",
    },
  ],
  pageable: {
    sort: {
      sorted: false,
      unsorted: true,
    },
    offset: 0,
    pageSize: 10,
    pageNumber: 0,
    unpaged: false,
    paged: true,
  },
  last: true,
  totalElements: 13,
  totalPages: 2,
  size: 10,
  number: 0,
  sort: {
    sorted: false,
    unsorted: true,
  },
  numberOfElements: 10,
  first: true,
};
export const cityList = ["Karachi", "Multan", "Lahore", "Islamabad"];
export const areaSegment = ["Gul Ahmed", "Khadi", "J.", "Bonanza"];
export const topDataSource = [
  { url: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png", id: "11" },
  { url: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png", id: "12" },
  { url: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png", id: "13" },
  { url: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png", id: "14" },
  { url: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png", id: "15" },
  { url: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png", id: "16" },
  { url: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png", id: "17" },
  { url: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png", id: "18" },
  { url: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png", id: "19" },
];

export const lowerDataSource = [
  {
    title: "Example",
    screenBannerPreview: "Example",
    type: "Example",
    cardtype: "Example",
    cardImage: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    id: "11",
  },
  {
    title: "Example",
    screenBannerPreview: "Example",
    type: "Example",
    cardtype: "Example",
    cardImage: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    id: "12",
  },
  {
    title: "Example",
    screenBannerPreview: "Example",
    type: "Example",
    cardtype: "Example",
    cardImage: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    id: "13",
  },
  {
    title: "Example",
    screenBannerPreview: "Example",
    type: "Example",
    cardtype: "Example",
    cardImage: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    id: "11",
  },
  {
    title: "Example",
    screenBannerPreview: "Example",
    type: "Example",
    cardtype: "Example",
    cardImage: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    id: "11",
  },
];
