export const sessionUsers = {
  content: [
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-1",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_Consumer_Add: true,
        UserManagement_Consumer_Edit: true,
        UserManagement_Consumer_List: true,
        UserManagement_Merchant_Add: true,
        UserManagement_Merchant_Edit: true,
        UserManagement_Merchant_List: true,
        PartnerManagement_View: true,
        PartnerManagement_AreaSegment_Add: true,
        PartnerManagement_AreaSegment_Edit: true,
        PartnerManagement_AreaSegment_List: true,
        PartnerManagement_Brand_List: true,
        PartnerManagement_Partner_List: true,
        DealManagement_View: true,
        DealManagement_Book_List: true,
        DealManagement_BookPurchaseRequest_List: true,
        DealManagement_Campaign_List: true,
        DealManagement_Category_Add: true,
        DealManagement_Category_Edit: true,
        DealManagement_Category_List: true,
        DealManagement_Deal_Add: true,
        DealManagement_Deal_Edit: true,
        DealManagement_Deal_List: true,
        CorporateCustomerManagement_View: true,
        CorporateCustomerManagement_CorporateCustomer_List: true,
        CorporateCustomerManagement_CorporateCustomer_Add: true,
        CorporateCustomerManagement_CorporateCustomer_Edit: true,
        CorporateCustomerManagement_BookSubscription_List: true,
      },

      userType: "Merchant",

      userAgent: "Firefox",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-2",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_Consumer_Add: true,
        UserManagement_Consumer_Edit: true,
        UserManagement_Consumer_List: true,
        UserManagement_Merchant_Add: true,
        UserManagement_Merchant_Edit: true,
        UserManagement_Merchant_List: true,

        PartnerManagement_View: true,
        PartnerManagement_AreaSegment_Add: true,
        PartnerManagement_AreaSegment_Edit: true,
        PartnerManagement_AreaSegment_List: true,
        PartnerManagement_Brand_List: true,
        PartnerManagement_Partner_List: true,
        DealManagement_View: true,
        DealManagement_Book_List: true,
        DealManagement_BookPurchaseRequest_List: true,
        DealManagement_Campaign_List: true,
        DealManagement_Category_Add: true,
        DealManagement_Category_Edit: true,
        DealManagement_Category_List: true,
        DealManagement_Deal_Add: true,
        DealManagement_Deal_Edit: true,
        DealManagement_Deal_List: true,
        CorporateCustomerManagement_View: true,
        CorporateCustomerManagement_CorporateCustomer_List: true,
        CorporateCustomerManagement_CorporateCustomer_Add: true,
        CorporateCustomerManagement_CorporateCustomer_Edit: true,
        CorporateCustomerManagement_BookSubscription_List: true,
      },

      userType: "Merchant",

      userAgent: "Firefox",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-3",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_Consumer_List: true,
      },

      userType: "Consumers",
      userAgent: "IOS",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-4",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_Consumer_List: true,
      },

      userType: "Consumers",
      userAgent: "Crome",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-5",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_Consumer_List: true,
      },

      userType: "Consumers",
      userAgent: "Crome",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-6",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_Consumer_List: true,
      },

      userType: "Consumers",
      userAgent: "Android",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-7",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_Consumer_List: true,
      },

      userType: "Consumers",
      userAgent: "Android",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-8",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_Consumer_List: true,
      },

      userType: "Consumers",
      userAgent: "IOS",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-9",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_View: true,
        UserManagement_Session_List: true,
        UserManagement_Admin_Add: true,
        UserManagement_Admin_Delete: true,
        UserManagement_Admin_Edit: true,
        UserManagement_Admin_List: true,
        UserManagement_Consumer_Add: true,
        UserManagement_Consumer_Edit: true,
        UserManagement_Consumer_List: true,
        UserManagement_Merchant_Add: true,
        UserManagement_Merchant_Edit: true,
        UserManagement_Merchant_List: true,
        PartnerManagement_View: true,
        PartnerManagement_AreaSegment_Add: true,
        PartnerManagement_AreaSegment_Edit: true,
        PartnerManagement_AreaSegment_List: true,
        PartnerManagement_Brand_List: true,
        PartnerManagement_Partner_List: true,
        DealManagement_View: true,
        DealManagement_Book_List: true,
        DealManagement_BookPurchaseRequest_List: true,
        DealManagement_Campaign_List: true,
        DealManagement_Category_Add: true,
        DealManagement_Category_Edit: true,
        DealManagement_Category_List: true,
        DealManagement_Deal_Add: true,
        DealManagement_Deal_Edit: true,
        DealManagement_Deal_List: true,
        Reports_View: true,
        Reports_DealRedeem_List: true,
        Reports_BoorPurchase_List: true,
        Reports_Campaign_List: true,
        CorporateCustomerManagement_View: true,
        CorporateCustomerManagement_CorporateCustomer_List: true,
        CorporateCustomerManagement_CorporateCustomer_Add: true,
        CorporateCustomerManagement_CorporateCustomer_Edit: true,
        CorporateCustomerManagement_BookSubscription_List: true,
      },

      userType: "Admin",
      userAgent: "IOS",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-10",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_View: true,
        UserManagement_Session_List: true,
        UserManagement_Admin_Add: true,
        UserManagement_Admin_Delete: true,
        UserManagement_Admin_Edit: true,
        UserManagement_Admin_List: true,
        UserManagement_Consumer_Add: true,
        UserManagement_Consumer_Edit: true,
        UserManagement_Consumer_List: true,
        UserManagement_Merchant_Add: true,
        UserManagement_Merchant_Edit: true,
        UserManagement_Merchant_List: true,
        PartnerManagement_View: true,
        PartnerManagement_AreaSegment_Add: true,
        PartnerManagement_AreaSegment_Edit: true,
        PartnerManagement_AreaSegment_List: true,
        PartnerManagement_Brand_List: true,
        PartnerManagement_Partner_List: true,
        DealManagement_View: true,
        DealManagement_Book_List: true,
        DealManagement_BookPurchaseRequest_List: true,
        DealManagement_Campaign_List: true,
        DealManagement_Category_Add: true,
        DealManagement_Category_Edit: true,
        DealManagement_Category_List: true,
        DealManagement_Deal_Add: true,
        DealManagement_Deal_Edit: true,
        DealManagement_Deal_List: true,
        Reports_View: true,
        Reports_DealRedeem_List: true,
        Reports_BoorPurchase_List: true,
        Reports_Campaign_List: true,
        CorporateCustomerManagement_View: true,
        CorporateCustomerManagement_CorporateCustomer_List: true,
        CorporateCustomerManagement_CorporateCustomer_Add: true,
        CorporateCustomerManagement_CorporateCustomer_Edit: true,
        CorporateCustomerManagement_BookSubscription_List: true,
      },

      userType: "Admin",

      userAgent: "IOS",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-11",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_View: true,
        UserManagement_Session_List: true,
        UserManagement_Admin_Add: true,
        UserManagement_Admin_Delete: true,
        UserManagement_Admin_Edit: true,
        UserManagement_Admin_List: true,
        UserManagement_Consumer_Add: true,
        UserManagement_Consumer_Edit: true,
        UserManagement_Consumer_List: true,
        UserManagement_Merchant_Add: true,
        UserManagement_Merchant_Edit: true,
        UserManagement_Merchant_List: true,
        PartnerManagement_View: true,
        PartnerManagement_AreaSegment_Add: true,
        PartnerManagement_AreaSegment_Edit: true,
        PartnerManagement_AreaSegment_List: true,
        PartnerManagement_Brand_List: true,
        PartnerManagement_Partner_List: true,
        DealManagement_View: true,
        DealManagement_Book_List: true,
        DealManagement_BookPurchaseRequest_List: true,
        DealManagement_Campaign_List: true,
        DealManagement_Category_Add: true,
        DealManagement_Category_Edit: true,
        DealManagement_Category_List: true,
        DealManagement_Deal_Add: true,
        DealManagement_Deal_Edit: true,
        DealManagement_Deal_List: true,
        Reports_View: true,
        Reports_DealRedeem_List: true,
        Reports_BoorPurchase_List: true,
        Reports_Campaign_List: true,
        CorporateCustomerManagement_View: true,
        CorporateCustomerManagement_CorporateCustomer_List: true,
        CorporateCustomerManagement_CorporateCustomer_Add: true,
        CorporateCustomerManagement_CorporateCustomer_Edit: true,
        CorporateCustomerManagement_BookSubscription_List: true,
      },

      userType: "Admin",

      userAgent: "IOS",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-12",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_View: true,
        UserManagement_Session_List: true,
        UserManagement_Admin_Add: true,
        UserManagement_Admin_Delete: true,
        UserManagement_Admin_Edit: true,
        UserManagement_Admin_List: true,
        UserManagement_Consumer_Add: true,
        UserManagement_Consumer_Edit: true,
        UserManagement_Consumer_List: true,
        UserManagement_Merchant_Add: true,
        UserManagement_Merchant_Edit: true,
        UserManagement_Merchant_List: true,
        PartnerManagement_View: true,
        PartnerManagement_AreaSegment_Add: true,
        PartnerManagement_AreaSegment_Edit: true,
        PartnerManagement_AreaSegment_List: true,
        PartnerManagement_Brand_List: true,
        PartnerManagement_Partner_List: true,
        DealManagement_View: true,
        DealManagement_Book_List: true,
        DealManagement_BookPurchaseRequest_List: true,
        DealManagement_Campaign_List: true,
        DealManagement_Category_Add: true,
        DealManagement_Category_Edit: true,
        DealManagement_Category_List: true,
        DealManagement_Deal_Add: true,
        DealManagement_Deal_Edit: true,
        DealManagement_Deal_List: true,
        Reports_View: true,
        Reports_DealRedeem_List: true,
        Reports_BoorPurchase_List: true,
        Reports_Campaign_List: true,
        CorporateCustomerManagement_View: true,
        CorporateCustomerManagement_CorporateCustomer_List: true,
        CorporateCustomerManagement_CorporateCustomer_Add: true,
        CorporateCustomerManagement_CorporateCustomer_Edit: true,
        CorporateCustomerManagement_BookSubscription_List: true,
      },

      userType: "Admin",

      userAgent: "Safari",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-13",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_View: true,
        UserManagement_Session_List: true,
        UserManagement_Admin_Add: true,
        UserManagement_Admin_Delete: true,
        UserManagement_Admin_Edit: true,
        UserManagement_Admin_List: true,
        UserManagement_Consumer_Add: true,
        UserManagement_Consumer_Edit: true,
        UserManagement_Consumer_List: true,
        UserManagement_Merchant_Add: true,
        UserManagement_Merchant_Edit: true,
        UserManagement_Merchant_List: true,
        PartnerManagement_View: true,
        PartnerManagement_AreaSegment_Add: true,
        PartnerManagement_AreaSegment_Edit: true,
        PartnerManagement_AreaSegment_List: true,
        PartnerManagement_Brand_List: true,
        PartnerManagement_Partner_List: true,
        DealManagement_View: true,
        DealManagement_Book_List: true,
        DealManagement_BookPurchaseRequest_List: true,
        DealManagement_Campaign_List: true,
        DealManagement_Category_Add: true,
        DealManagement_Category_Edit: true,
        DealManagement_Category_List: true,
        DealManagement_Deal_Add: true,
        DealManagement_Deal_Edit: true,
        DealManagement_Deal_List: true,
        Reports_View: true,
        Reports_DealRedeem_List: true,
        Reports_BoorPurchase_List: true,
        Reports_Campaign_List: true,
        CorporateCustomerManagement_View: true,
        CorporateCustomerManagement_CorporateCustomer_List: true,
        CorporateCustomerManagement_CorporateCustomer_Add: true,
        CorporateCustomerManagement_CorporateCustomer_Edit: true,
        CorporateCustomerManagement_BookSubscription_List: true,
      },

      userType: "Admin",

      userAgent: "Safari",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-14",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_View: true,
        UserManagement_Session_List: true,
        UserManagement_Admin_Add: true,
        UserManagement_Admin_Delete: true,
        UserManagement_Admin_Edit: true,
        UserManagement_Admin_List: true,
        UserManagement_Consumer_Add: true,
        UserManagement_Consumer_Edit: true,
        UserManagement_Consumer_List: true,
        UserManagement_Merchant_Add: true,
        UserManagement_Merchant_Edit: true,
        UserManagement_Merchant_List: true,
        PartnerManagement_View: true,
        PartnerManagement_AreaSegment_Add: true,
        PartnerManagement_AreaSegment_Edit: true,
        PartnerManagement_AreaSegment_List: true,
        PartnerManagement_Brand_List: true,
        PartnerManagement_Partner_List: true,
        DealManagement_View: true,
        DealManagement_Book_List: true,
        DealManagement_BookPurchaseRequest_List: true,
        DealManagement_Campaign_List: true,
        DealManagement_Category_Add: true,
        DealManagement_Category_Edit: true,
        DealManagement_Category_List: true,
        DealManagement_Deal_Add: true,
        DealManagement_Deal_Edit: true,
        DealManagement_Deal_List: true,
        Reports_View: true,
        Reports_DealRedeem_List: true,
        Reports_BoorPurchase_List: true,
        Reports_Campaign_List: true,
        CorporateCustomerManagement_View: true,
        CorporateCustomerManagement_CorporateCustomer_List: true,
        CorporateCustomerManagement_CorporateCustomer_Add: true,
        CorporateCustomerManagement_CorporateCustomer_Edit: true,
        CorporateCustomerManagement_BookSubscription_List: true,
      },

      userType: "Admin",

      userAgent: "Opera Mini",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-15",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_View: true,
        UserManagement_Session_List: true,
        UserManagement_Admin_Add: true,
        UserManagement_Admin_Delete: true,
        UserManagement_Admin_Edit: true,
        UserManagement_Admin_List: true,
        UserManagement_Consumer_Add: true,
        UserManagement_Consumer_Edit: true,
        UserManagement_Consumer_List: true,
        UserManagement_Merchant_Add: true,
        UserManagement_Merchant_Edit: true,
        UserManagement_Merchant_List: true,
        PartnerManagement_View: true,
        PartnerManagement_AreaSegment_Add: true,
        PartnerManagement_AreaSegment_Edit: true,
        PartnerManagement_AreaSegment_List: true,
        PartnerManagement_Brand_List: true,
        PartnerManagement_Partner_List: true,
        DealManagement_View: true,
        DealManagement_Book_List: true,
        DealManagement_BookPurchaseRequest_List: true,
        DealManagement_Campaign_List: true,
        DealManagement_Category_Add: true,
        DealManagement_Category_Edit: true,
        DealManagement_Category_List: true,
        DealManagement_Deal_Add: true,
        DealManagement_Deal_Edit: true,
        DealManagement_Deal_List: true,
        Reports_View: true,
        Reports_DealRedeem_List: true,
        Reports_BoorPurchase_List: true,
        Reports_Campaign_List: true,
        CorporateCustomerManagement_View: true,
        CorporateCustomerManagement_CorporateCustomer_List: true,
        CorporateCustomerManagement_CorporateCustomer_Add: true,
        CorporateCustomerManagement_CorporateCustomer_Edit: true,
        CorporateCustomerManagement_BookSubscription_List: true,
      },

      userType: "Admin",

      userAgent: "Opera Mini",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-16",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_View: true,
        UserManagement_Session_List: true,
        UserManagement_Admin_Add: true,
        UserManagement_Admin_Delete: true,
        UserManagement_Admin_Edit: true,
        UserManagement_Admin_List: true,
        UserManagement_Consumer_Add: true,
        UserManagement_Consumer_Edit: true,
        UserManagement_Consumer_List: true,
        UserManagement_Merchant_Add: true,
        UserManagement_Merchant_Edit: true,
        UserManagement_Merchant_List: true,
        PartnerManagement_View: true,
        PartnerManagement_AreaSegment_Add: true,
        PartnerManagement_AreaSegment_Edit: true,
        PartnerManagement_AreaSegment_List: true,
        PartnerManagement_Brand_List: true,
        PartnerManagement_Partner_List: true,
        DealManagement_View: true,
        DealManagement_Book_List: true,
        DealManagement_BookPurchaseRequest_List: true,
        DealManagement_Campaign_List: true,
        DealManagement_Category_Add: true,
        DealManagement_Category_Edit: true,
        DealManagement_Category_List: true,
        DealManagement_Deal_Add: true,
        DealManagement_Deal_Edit: true,
        DealManagement_Deal_List: true,
        Reports_View: true,
        Reports_DealRedeem_List: true,
        Reports_BoorPurchase_List: true,
        Reports_Campaign_List: true,
        CorporateCustomerManagement_View: true,
        CorporateCustomerManagement_CorporateCustomer_List: true,
        CorporateCustomerManagement_CorporateCustomer_Add: true,
        CorporateCustomerManagement_CorporateCustomer_Edit: true,
        CorporateCustomerManagement_BookSubscription_List: true,
      },

      userType: "Admin",

      userAgent: "Opera Mini",
    },
    {
      createdAt: "2020-04-07T10:56:35.748+0000",
      updatedAt: "2020-04-07T10:56:35.812+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-17",
      fullName: "muneer sahab 2",
      emailAddress: "muneershah2@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_Consumer_Add: true,
        UserManagement_Consumer_Edit: true,
        UserManagement_Consumer_List: true,
        UserManagement_Merchant_Add: true,
        UserManagement_Merchant_Edit: true,
        UserManagement_Merchant_List: true,

        PartnerManagement_View: true,
        PartnerManagement_AreaSegment_Add: true,
        PartnerManagement_AreaSegment_Edit: true,
        PartnerManagement_AreaSegment_List: true,
        PartnerManagement_Brand_List: true,
        PartnerManagement_Partner_List: true,
        DealManagement_View: true,
        DealManagement_Book_List: true,
        DealManagement_BookPurchaseRequest_List: true,
        DealManagement_Campaign_List: true,
        DealManagement_Category_Add: true,
        DealManagement_Category_Edit: true,
        DealManagement_Category_List: true,
        DealManagement_Deal_Add: true,
        DealManagement_Deal_Edit: true,
        DealManagement_Deal_List: true,
        CorporateCustomerManagement_View: true,
        CorporateCustomerManagement_CorporateCustomer_List: true,
        CorporateCustomerManagement_CorporateCustomer_Add: true,
        CorporateCustomerManagement_CorporateCustomer_Edit: true,
        CorporateCustomerManagement_BookSubscription_List: true,
      },

      userType: "Merchant",
      userAgent: "Firefox",
    },
    {
      createdAt: "2020-04-07T10:57:56.676+0000",
      updatedAt: "2020-04-07T10:57:56.689+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-18",
      fullName: "muneer sahab 3",
      emailAddress: "muneershah3@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_Consumer_Add: true,
        UserManagement_Consumer_Edit: true,
        UserManagement_Consumer_List: true,
        UserManagement_Merchant_Add: true,
        UserManagement_Merchant_Edit: true,
        UserManagement_Merchant_List: true,

        PartnerManagement_View: true,
        PartnerManagement_AreaSegment_Add: true,
        PartnerManagement_AreaSegment_Edit: true,
        PartnerManagement_AreaSegment_List: true,
        PartnerManagement_Brand_List: true,
        PartnerManagement_Partner_List: true,
        DealManagement_View: true,
        DealManagement_Book_List: true,
        DealManagement_BookPurchaseRequest_List: true,
        DealManagement_Campaign_List: true,
        DealManagement_Category_Add: true,
        DealManagement_Category_Edit: true,
        DealManagement_Category_List: true,
        DealManagement_Deal_Add: true,
        DealManagement_Deal_Edit: true,
        DealManagement_Deal_List: true,
        CorporateCustomerManagement_View: true,
        CorporateCustomerManagement_CorporateCustomer_List: true,
        CorporateCustomerManagement_CorporateCustomer_Add: true,
        CorporateCustomerManagement_CorporateCustomer_Edit: true,
        CorporateCustomerManagement_BookSubscription_List: true,
      },

      userType: "Merchant",

      userAgent: "Firefox",
    },
    {
      createdAt: "2020-04-07T10:58:35.217+0000",
      updatedAt: "2020-04-07T10:58:35.220+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-19",
      fullName: "muneer sahab 3",
      emailAddress: "muneershah4@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_Consumer_Add: true,
        UserManagement_Consumer_Edit: true,
        UserManagement_Consumer_List: true,
        UserManagement_Merchant_Add: true,
        UserManagement_Merchant_Edit: true,
        UserManagement_Merchant_List: true,

        PartnerManagement_View: true,
        PartnerManagement_AreaSegment_Add: true,
        PartnerManagement_AreaSegment_Edit: true,
        PartnerManagement_AreaSegment_List: true,
        PartnerManagement_Brand_List: true,
        PartnerManagement_Partner_List: true,
        DealManagement_View: true,
        DealManagement_Book_List: true,
        DealManagement_BookPurchaseRequest_List: true,
        DealManagement_Campaign_List: true,
        DealManagement_Category_Add: true,
        DealManagement_Category_Edit: true,
        DealManagement_Category_List: true,
        DealManagement_Deal_Add: true,
        DealManagement_Deal_Edit: true,
        DealManagement_Deal_List: true,
        CorporateCustomerManagement_View: true,
        CorporateCustomerManagement_CorporateCustomer_List: true,
        CorporateCustomerManagement_CorporateCustomer_Add: true,
        CorporateCustomerManagement_CorporateCustomer_Edit: true,
        CorporateCustomerManagement_BookSubscription_List: true,
      },

      userType: "Merchant",

      userAgent: "Firefox",
    },
    {
      createdAt: "2020-04-07T11:44:56.928+0000",
      updatedAt: "2020-04-07T11:44:57.042+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-20",
      fullName: "muneer sahab 3",
      emailAddress: "muneershah5@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_Consumer_Add: true,
        UserManagement_Consumer_Edit: true,
        UserManagement_Consumer_List: true,
        UserManagement_Merchant_Add: true,
        UserManagement_Merchant_Edit: true,
        UserManagement_Merchant_List: true,

        PartnerManagement_View: true,
        PartnerManagement_AreaSegment_Add: true,
        PartnerManagement_AreaSegment_Edit: true,
        PartnerManagement_AreaSegment_List: true,
        PartnerManagement_Brand_List: true,
        PartnerManagement_Partner_List: true,
        DealManagement_View: true,
        DealManagement_Book_List: true,
        DealManagement_BookPurchaseRequest_List: true,
        DealManagement_Campaign_List: true,
        DealManagement_Category_Add: true,
        DealManagement_Category_Edit: true,
        DealManagement_Category_List: true,
        DealManagement_Deal_Add: true,
        DealManagement_Deal_Edit: true,
        DealManagement_Deal_List: true,
        CorporateCustomerManagement_View: true,
        CorporateCustomerManagement_CorporateCustomer_List: true,
        CorporateCustomerManagement_CorporateCustomer_Add: true,
        CorporateCustomerManagement_CorporateCustomer_Edit: true,
        CorporateCustomerManagement_BookSubscription_List: true,
      },

      userType: "Merchant",

      userAgent: "Firefox",
    },
    {
      createdAt: "2020-04-07T11:45:20.998+0000",
      updatedAt: "2020-04-07T12:16:10.179+0000",
      createdBy: "osama pasha",
      updatedBy: "osama pasha",
      userId: "nisum-21",
      fullName: "muneer sahab 378989",
      emailAddress: "muneershah6@nisumadmin.com",
      cellPhoneNumber: "012-1541245124",
      image: [
        {
          type: "mobile",
          imageUrl: "https://www.forbes.com/sites/jimgorzelany/2019/07/23/here-are-the-coolest-new-cars-for-2020/",
        },
      ],
      capabilities: {
        UserManagement_Consumer_Add: true,
        UserManagement_Consumer_Edit: true,
        UserManagement_Consumer_List: true,
        UserManagement_Merchant_Add: true,
        UserManagement_Merchant_Edit: true,
        UserManagement_Merchant_List: true,

        PartnerManagement_View: true,
        PartnerManagement_AreaSegment_Add: true,
        PartnerManagement_AreaSegment_Edit: true,
        PartnerManagement_AreaSegment_List: true,
        PartnerManagement_Brand_List: true,
        PartnerManagement_Partner_List: true,
        DealManagement_View: true,
        DealManagement_Book_List: true,
        DealManagement_BookPurchaseRequest_List: true,
        DealManagement_Campaign_List: true,
        DealManagement_Category_Add: true,
        DealManagement_Category_Edit: true,
        DealManagement_Category_List: true,
        DealManagement_Deal_Add: true,
        DealManagement_Deal_Edit: true,
        DealManagement_Deal_List: true,
        CorporateCustomerManagement_View: true,
        CorporateCustomerManagement_CorporateCustomer_List: true,
        CorporateCustomerManagement_CorporateCustomer_Add: true,
        CorporateCustomerManagement_CorporateCustomer_Edit: true,
        CorporateCustomerManagement_BookSubscription_List: true,
      },

      userType: "Merchant",

      userAgent: "Firefox",
    },
  ],

  userAgent: [
    { text: "Firefox", value: "Firefox" },
    { text: "Crome", value: "Crome" },
    { text: "Android", value: "Android" },
    { text: "IOS", value: "IOS" },
  ],
};
