// - Columns
//   - Selection chk box
//   - redemptionId
//   - voucherId
//   - voucherName
//   - redeemedAt | redemptionTimestamp
//   - redeemedCode
//   - consumerId
//   - consumerName
//   - consumerContact
//   - redemptionStatus (inprogress, redeemed, completed, rejected, withdrawed)
//   - type (redemption with code, redemption with QRCode)
//   - authorizationCode
//   - rejectionReason

export const voucherRedemption = {
  content: [
    {
      code: "61ce8106-100c-4a1d-b172-eccb0f91e129", // redemptionId
      voucherId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      voucherName: "voucherName",
      redeemedAt: "2020-01-01",
      redeemedCode: "redeemedCode",
      consumerId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      consumerName: "Consumer Name",
      consumerContact: "Consumer Contact",
      redemptionStatus: "Redemption Status", // inprogress, redeemed, completed, rejected, withdrawed
      type: "Type",
      authorizationCode: "Authorization Code",
      rejectionReason: "Rejection Reason",
    },
    {
      code: "61ce8106-100c-4a1d-b172-eccb0f91e129", // redemptionId
      voucherId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      voucherName: "voucherName",
      redeemedAt: "2020-01-01",
      redeemedCode: "redeemedCode",
      consumerId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      consumerName: "Consumer Name",
      consumerContact: "Consumer Contact",
      redemptionStatus: "Redemption Status", // inprogress, redeemed, completed, rejected, withdrawed
      type: "Type",
      authorizationCode: "Authorization Code",
      rejectionReason: "Rejection Reason",
    },
    {
      code: "61ce8106-100c-4a1d-b172-eccb0f91e129", // redemptionId
      voucherId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      voucherName: "voucherName",
      redeemedAt: "2020-01-01",
      redeemedCode: "redeemedCode",
      consumerId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      consumerName: "Consumer Name",
      consumerContact: "Consumer Contact",
      redemptionStatus: "Redemption Status", // inprogress, redeemed, completed, rejected, withdrawed
      type: "Type",
      authorizationCode: "Authorization Code",
      rejectionReason: "Rejection Reason",
    },
    {
      code: "61ce8106-100c-4a1d-b172-eccb0f91e129", // redemptionId
      voucherId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      voucherName: "voucherName",
      redeemedAt: "2020-01-01",
      redeemedCode: "redeemedCode",
      consumerId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      consumerName: "Consumer Name",
      consumerContact: "Consumer Contact",
      redemptionStatus: "Redemption Status", // inprogress, redeemed, completed, rejected, withdrawed
      type: "Type",
      authorizationCode: "Authorization Code",
      rejectionReason: "Rejection Reason",
    },
    {
      code: "61ce8106-100c-4a1d-b172-eccb0f91e129", // redemptionId
      voucherId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      voucherName: "voucherName",
      redeemedAt: "2020-01-01",
      redeemedCode: "redeemedCode",
      consumerId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      consumerName: "Consumer Name",
      consumerContact: "Consumer Contact",
      redemptionStatus: "Redemption Status", // inprogress, redeemed, completed, rejected, withdrawed
      type: "Type",
      authorizationCode: "Authorization Code",
      rejectionReason: "Rejection Reason",
    },
    {
      code: "61ce8106-100c-4a1d-b172-eccb0f91e129", // redemptionId
      voucherId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      voucherName: "voucherName",
      redeemedAt: "2020-01-01",
      redeemedCode: "redeemedCode",
      consumerId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      consumerName: "Consumer Name",
      consumerContact: "Consumer Contact",
      redemptionStatus: "Redemption Status", // inprogress, redeemed, completed, rejected, withdrawed
      type: "Type",
      authorizationCode: "Authorization Code",
      rejectionReason: "Rejection Reason",
    },
    {
      code: "61ce8106-100c-4a1d-b172-eccb0f91e129", // redemptionId
      voucherId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      voucherName: "voucherName",
      redeemedAt: "2020-01-01",
      redeemedCode: "redeemedCode",
      consumerId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      consumerName: "Consumer Name",
      consumerContact: "Consumer Contact",
      redemptionStatus: "Redemption Status", // inprogress, redeemed, completed, rejected, withdrawed
      type: "Type",
      authorizationCode: "Authorization Code",
      rejectionReason: "Rejection Reason",
    },
    {
      code: "61ce8106-100c-4a1d-b172-eccb0f91e129", // redemptionId
      voucherId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      voucherName: "voucherName",
      redeemedAt: "2020-01-01",
      redeemedCode: "redeemedCode",
      consumerId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      consumerName: "Consumer Name",
      consumerContact: "Consumer Contact",
      redemptionStatus: "Redemption Status", // inprogress, redeemed, completed, rejected, withdrawed
      type: "Type",
      authorizationCode: "Authorization Code",
      rejectionReason: "Rejection Reason",
    },
    {
      code: "61ce8106-100c-4a1d-b172-eccb0f91e129", // redemptionId
      voucherId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      voucherName: "voucherName",
      redeemedAt: "2020-01-01",
      redeemedCode: "redeemedCode",
      consumerId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      consumerName: "Consumer Name",
      consumerContact: "Consumer Contact",
      redemptionStatus: "Redemption Status", // inprogress, redeemed, completed, rejected, withdrawed
      type: "Type",
      authorizationCode: "Authorization Code",
      rejectionReason: "Rejection Reason",
    },
    {
      code: "61ce8106-100c-4a1d-b172-eccb0f91e129", // redemptionId
      voucherId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      voucherName: "voucherName",
      redeemedAt: "2020-01-01",
      redeemedCode: "redeemedCode",
      consumerId: "61ce8106-100c-4a1d-b172-eccb0f91e129",
      consumerName: "Consumer Name",
      consumerContact: "Consumer Contact",
      redemptionStatus: "Redemption Status", // inprogress, redeemed, completed, rejected, withdrawed
      type: "Type",
      authorizationCode: "Authorization Code",
      rejectionReason: "Rejection Reason",
    },
  ],
  pageable: {
    sort: {
      sorted: false,
      unsorted: true,
    },
    offset: 0,
    pageSize: 10,
    pageNumber: 0,
    unpaged: false,
    paged: true,
  },
  last: true,
  totalElements: 14,
  totalPages: 2,
  size: 10,
  number: 0,
  sort: {
    sorted: false,
    unsorted: true,
  },
  numberOfElements: 10,
  first: true,
};
export const voucher = [
  { name: "ABC", code: "abc" },
  { name: "DEF", code: "def" },
  { name: "efg", code: "efg" },
];
export const createTicketResponse = {
  additionalInfo: null,
  authorizationCode: null,
  bookCode: null,
  bookName: null,
  brandCode: "8f225dc1-0b46-492b-8f90-80e7a23c18ca",
  brandName: "KFC",
  consumerCode: null,
  consumerDetail: null,
  consumerName: null,
  createdAt: 1589647441305,
  createdBy: "khalid@bgn.com",
  createdByUserCode: "9c8c78aa-016b-4c40-a100-dd9070947dc5",
  enabled: false,
  partnerCode: "5d8d5bcb-2ac3-43b4-9a9f-ca5406c52678",
  partnerName: "Lucky Mall",
  reason: "Service ERROR",
  recordStatus: null,
  redeemedTicketStatus: "REJECTED",
  redemptionType: "REDEEMED_WITH_CODE",
  saleAmount: null,
  updatedAt: 1589647491744,
  updatedBy: "khalid@bgn.com",
  updatedByUserCode: "9c8c78aa-016b-4c40-a100-dd9070947dc5",
  voucherDetail: null,
  voucherNumber: "IgEigcvpAH",
  voucherRedeemedDateTime: 0,
  voucherRedeemedTicketId: "5ec0185189cdd1730e26e50a",
  voucherSaving: null,
  voucherTitle: null,
};

export const allVouchers = {
  content: [
    {
      recordStatus: null,
      createdBy: "admin",
      createdAt: 0,
      updatedBy: null,
      updatedAt: 0,
      createdByUserCode: null,
      updatedByUserCode: null,
      voucherRedeemedTicketId: "5ebadc08c8170f8e78b15e3d",
      authorizationCode: null,
      voucherNumber: null,
      consumerCode: null,
      consumerName: null,
      bookCode: null,
      brandCode: "PART-001",
      brandName: "J.",
      partnerCode: "abccc-aaa-ddd",
      partnerName: "Dollmen Mall",
      areaSegmentCode: null,
      areaSegmentName: null,
      voucherRedeemedDateTime: 0,
      redeemedTicketStatus: "REJECTED",
      redemptionType: "REDEEMED_WITH_CODE",
      additionalInfo: null,
      saleAmount: null,
      rejectionReason: "Voucher number is not valid.",
      enabled: false,
    },
    {
      recordStatus: null,
      createdBy: "aaa@hormail.com",
      createdAt: 1589404973223,
      updatedBy: "aaa@hormail.com",
      updatedAt: 1589404973223,
      createdByUserCode: null,
      updatedByUserCode: null,
      voucherRedeemedTicketId: "5ebc652d1bd1766e9059452e",
      authorizationCode: null,
      voucherNumber: null,
      consumerCode: null,
      consumerName: null,
      bookCode: null,
      brandCode: "PART-001",
      brandName: "J.",
      partnerCode: "aaa-bbbb-ddd-ccc",
      partnerName: "Dollmen Mall",
      areaSegmentCode: null,
      areaSegmentName: null,
      voucherRedeemedDateTime: 0,
      redeemedTicketStatus: "COMPLETED",
      redemptionType: "REDEEMED_WITH_QR",
      additionalInfo: null,
      saleAmount: null,
      rejectionReason: null,
      enabled: false,
    },
    {
      recordStatus: null,
      createdBy: "aaa@hormail.com",
      createdAt: 1589405375348,
      updatedBy: "aaa@hormail.com",
      updatedAt: 1589405375348,
      createdByUserCode: "1223",
      updatedByUserCode: null,
      voucherRedeemedTicketId: "5ebc66bf61c26c1cc4a61220",
      authorizationCode: null,
      voucherNumber: null,
      consumerCode: null,
      consumerName: null,
      bookCode: null,
      brandCode: "PART-001",
      brandName: "J.",
      partnerCode: "aaa-bbbb-ddd-ccc",
      partnerName: "Dollmen Mall",
      areaSegmentCode: null,
      areaSegmentName: null,
      voucherRedeemedDateTime: 0,
      redeemedTicketStatus: "REJECTED",
      redemptionType: "REDEEMED_WITH_QR",
      additionalInfo: null,
      saleAmount: null,
      rejectionReason: null,
      enabled: false,
    },
    {
      recordStatus: null,
      createdBy: "aaa@hormail.com",
      createdAt: 1589443688944,
      updatedBy: "aaa@hormail.com",
      updatedAt: 1589443688944,
      createdByUserCode: "1223",
      updatedByUserCode: null,
      voucherRedeemedTicketId: "5ebcfc6976e0a7321b435e7a",
      authorizationCode: null,
      voucherNumber: null,
      consumerCode: null,
      consumerName: null,
      bookCode: null,
      brandCode: "PART-001",
      brandName: "J.",
      partnerCode: "aaa-bbbb-ddd-ccc",
      partnerName: "Dollmen Mall",
      areaSegmentCode: null,
      areaSegmentName: null,
      voucherRedeemedDateTime: 0,
      redeemedTicketStatus: "INPROGRESS",
      redemptionType: "REDEEMED_WITH_QR",
      additionalInfo: null,
      saleAmount: null,
      rejectionReason: null,
      enabled: false,
    },
    {
      recordStatus: null,
      createdBy: "aaa@hormail.com",
      createdAt: 1589472296401,
      updatedBy: "aaa@hormail.com",
      updatedAt: 1589472296401,
      createdByUserCode: "1223",
      updatedByUserCode: null,
      voucherRedeemedTicketId: "5ebd6c28ecfe3a776380e328",
      authorizationCode: null,
      voucherNumber: null,
      consumerCode: null,
      consumerName: null,
      bookCode: null,
      brandCode: "8f225dc1-0b46-492b-8f90-80e7a23c18ca",
      brandName: "KFC",
      partnerCode: "5d8d5bcb-2ac3-43b4-9a9f-ca5406c52678",
      partnerName: "Lucky Mall",
      areaSegmentCode: null,
      areaSegmentName: null,
      voucherRedeemedDateTime: 0,
      redeemedTicketStatus: "INPROGRESS",
      redemptionType: null,
      additionalInfo: null,
      saleAmount: null,
      rejectionReason: null,
      enabled: false,
    },
    {
      recordStatus: null,
      createdBy: "aaa@hormail.com",
      createdAt: 1589473106681,
      updatedBy: "aaa@hormail.com",
      updatedAt: 1589473106681,
      createdByUserCode: "1223",
      updatedByUserCode: null,
      voucherRedeemedTicketId: "5ebd6f525b4d94179467a905",
      authorizationCode: null,
      voucherNumber: null,
      consumerCode: null,
      consumerName: null,
      bookCode: null,
      brandCode: "8f225dc1-0b46-492b-8f90-80e7a23c18ca",
      brandName: "KFC",
      partnerCode: "5d8d5bcb-2ac3-43b4-9a9f-ca5406c52678",
      partnerName: "Lucky Mall",
      areaSegmentCode: null,
      areaSegmentName: null,
      voucherRedeemedDateTime: 0,
      redeemedTicketStatus: "INPROGRESS",
      redemptionType: null,
      additionalInfo: null,
      saleAmount: null,
      rejectionReason: null,
      enabled: false,
    },
    {
      recordStatus: null,
      createdBy: "aaa@hormail.com",
      createdAt: 1589473402177,
      updatedBy: "aaa@hormail.com",
      updatedAt: 1589473402177,
      createdByUserCode: "1223",
      updatedByUserCode: null,
      voucherRedeemedTicketId: "5ebd707a5b4d94179467a906",
      authorizationCode: null,
      voucherNumber: null,
      consumerCode: null,
      consumerName: null,
      bookCode: null,
      brandCode: "8f225dc1-0b46-492b-8f90-80e7a23c18ca",
      brandName: "KFC",
      partnerCode: "5d8d5bcb-2ac3-43b4-9a9f-ca5406c52678",
      partnerName: "Lucky Mall",
      areaSegmentCode: null,
      areaSegmentName: null,
      voucherRedeemedDateTime: 0,
      redeemedTicketStatus: "INPROGRESS",
      redemptionType: null,
      additionalInfo: null,
      saleAmount: null,
      rejectionReason: null,
      enabled: false,
    },
    {
      recordStatus: null,
      createdBy: "aaa@hormail.com",
      createdAt: 1589473545102,
      updatedBy: "aaa@hormail.com",
      updatedAt: 1589473545102,
      createdByUserCode: "1223",
      updatedByUserCode: null,
      voucherRedeemedTicketId: "5ebd71095b4d94179467a907",
      authorizationCode: null,
      voucherNumber: null,
      consumerCode: null,
      consumerName: null,
      bookCode: null,
      brandCode: "8f225dc1-0b46-492b-8f90-80e7a23c18ca",
      brandName: "KFC",
      partnerCode: "5d8d5bcb-2ac3-43b4-9a9f-ca5406c52678",
      partnerName: "Lucky Mall",
      areaSegmentCode: null,
      areaSegmentName: null,
      voucherRedeemedDateTime: 0,
      redeemedTicketStatus: "INPROGRESS",
      redemptionType: null,
      additionalInfo: null,
      saleAmount: null,
      rejectionReason: null,
      enabled: false,
    },
    {
      recordStatus: null,
      createdBy: "aaa@hormail.com",
      createdAt: 1589473775129,
      updatedBy: "aaa@hormail.com",
      updatedAt: 1589473775129,
      createdByUserCode: "1223",
      updatedByUserCode: null,
      voucherRedeemedTicketId: "5ebd71ef5b4d94179467a908",
      authorizationCode: null,
      voucherNumber: null,
      consumerCode: null,
      consumerName: null,
      bookCode: null,
      brandCode: "8f225dc1-0b46-492b-8f90-80e7a23c18ca",
      brandName: "KFC",
      partnerCode: "5d8d5bcb-2ac3-43b4-9a9f-ca5406c52678",
      partnerName: "Lucky Mall",
      areaSegmentCode: null,
      areaSegmentName: null,
      voucherRedeemedDateTime: 0,
      redeemedTicketStatus: "INPROGRESS",
      redemptionType: null,
      additionalInfo: null,
      saleAmount: null,
      rejectionReason: null,
      enabled: false,
    },
    {
      recordStatus: null,
      createdBy: "aaa@hormail.com",
      createdAt: 1589473809251,
      updatedBy: "aaa@hormail.com",
      updatedAt: 1589473809251,
      createdByUserCode: "1223",
      updatedByUserCode: null,
      voucherRedeemedTicketId: "5ebd72115b4d94179467a909",
      authorizationCode: null,
      voucherNumber: null,
      consumerCode: null,
      consumerName: null,
      bookCode: null,
      brandCode: "8f225dc1-0b46-492b-8f90-80e7a23c18ca",
      brandName: "KFC",
      partnerCode: "5d8d5bcb-2ac3-43b4-9a9f-ca5406c52678",
      partnerName: "Lucky Mall",
      areaSegmentCode: null,
      areaSegmentName: null,
      voucherRedeemedDateTime: 0,
      redeemedTicketStatus: "REJECTED",
      redemptionType: null,
      additionalInfo: null,
      saleAmount: null,
      rejectionReason: null,
      enabled: false,
    },
  ],
  pageable: {
    sort: { sorted: false, unsorted: true, empty: true },
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 2,
  totalElements: 11,
  last: false,
  size: 10,
  number: 0,
  sort: { sorted: false, unsorted: true, empty: true },
  numberOfElements: 10,
  first: true,
  empty: false,
};
