const appInitialState = {
  user: {
    loading: false,
    error: null,
    value: {},
    capabilities: [],
    notificationsData: {},
    list: [],
  },
  deals: {
    loading: false,
    selectedDealsLoading: false,
    popularDealLoading: false,
    error: null,
    value: {},
    list: [],
    selectedList: {},
    popularDeals: {},
    selected: {},
    filteredList: [],
  },
  areaSegment: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
    state: [],
    cities: [],
  },
  book: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },
  campaignStatus: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },
  admin: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },
  merchant: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },
  ui: {
    loading: false,
    error: false,
    isModalOpen: false,
  },
  consumer: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },
  dealCategory: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },
  corporateCustomer: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },
  partner: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
    filteredList: [],
  },
  profiler: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
    swimlanes: {},
  },
  bookSubscription: {
    loading: false,
    error: null,
    list: [],
    selected: {},
    locations: [],
  },
  changePartner: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },
  session: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },
  brand: {
    loading: false,
    bookLoading: false,
    error: null,
    value: {},
    list: [],
    filteredList: [],
    bookBrandList: {},
    selectedBookBrandList: {},
    selected: {},
  },
  bookOrder: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },
  campaign: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },
  voucherRedemption: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
    isModalShow: false,
  },
  designer: {
    loading: false,
    error: null,
    value: {},
    selected: {},
  },
  bookPurchaseReport: {
    loading: false,
    error: null,
    value: {},
    list: [],
  },
  billingPlan: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
    filteredList: [],
    locations: [],
  },
  merchantDashboard: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },
  participant: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },
  volunteer: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },
  mosque: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },
  musalliAttendanceDetailReport: {
    loading: false,
    error: null,
    value: {},
    list: [],
    selected: {},
  },

  activeMosqueBySession: {
    mosqueOptionLoading: false,
    mosqueOptionerror: null,
    mosqueOptionvalue: {},
    mosqueOptionlist: [],
    mosqueOptionselected: {},
  },
};

export default appInitialState;
